import {Materials} from '/workbench/frontend/components/materials.js';
import {versionComparison} from '/workbench/frontend/components/version-comparison.js';
import {tableComparisonMarkup,blockComparisonMarkup,orderMarkup} from '/workbench/frontend/components/collaboration.js';
const q=s=>document.querySelector(s),m=new Materials(),requests=[];
const colName=n=>{let value='';while(n){n--;value=String.fromCharCode(65+n%26)+value;n=Math.floor(n/26);}return value;};
const sheets=[{name:'Water',state:'visible',rows:240,columns:32},{name:'Other',state:'visible',rows:10,columns:2}];
Object.assign(m,{q,root:document.querySelector('main'),id:'synthetic-sheet',token:{},state:{actor:{id:'fixture'}},material:{id:'synthetic-sheet',source:{content_hash:'fixture-sheet-hash'},collaboration:{view:'personal'},scope:[]},draft:{blocks:[{id:'c23',text:'Passage linked only to C23',source_refs:[{sheet:'Water',cell_range:'C23'}]},{id:'c121',text:'Passage linked to exact absolute range',source_refs:[{sheet:'Water',cell_range:'$C$121:$D$122'}]},{id:'c81',text:'Passage linked only to C81',source_refs:[{sheet:'Water',cell_range:'C81'}]}]},captureDisclosures(){},documentInformationMarkup:()=>'',message:text=>q('#status').textContent=text,dialog(html,bind){const d=q('#mw-dialog');d.innerHTML=html+'<button id="close">Close</button>';d.querySelector('#close').onclick=()=>d.close();if(!d.open)d.showModal();bind?.(d);},jumpToBlock(index){q('#status').textContent='Located: '+this.draft.blocks[index].text;},openingRequest:async path=>{
 requests.push(path);q('#log').textContent=requests.join('\n');const params=new URL(path,location.origin).searchParams,sheet=params.get('sheet')||'Water',spec=sheets.find(s=>s.name===sheet)||sheets[1],row=Number(params.get('row')||1),column=Number(params.get('column')||1),row_count=Math.min(80,spec.rows-row+1),column_count=Math.min(4,spec.columns-column+1);
 if(q('#delay').checked){q('#delay').checked=false;await new Promise(r=>setTimeout(r,1500));}
 if(row===81&&q('#fail-append').checked){q('#fail-append').checked=false;throw Error('Synthetic continuation failure');}
 return {kind:'spreadsheet',sheet:spec.name,sheets,row,column,row_count,column_count,rows:spec.rows,columns:spec.columns,source_sha256:'fixture-sheet-hash',merged:[],warnings:[],cells:Array.from({length:Math.max(0,row_count)},(_,r)=>Array.from({length:Math.max(0,column_count)},(_,c)=>({address:colName(column+c)+(row+r),value:'Saved '+colName(column+c)+(row+r)})))};
}});
m.root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='reader-linked')m.showLinkedBlocks();else m.readerAction(b.dataset.action).catch(error=>m.message(error.message));});
q('#reset-sheet').onclick=()=>m.loadReader({sheet:'Water',row:1,column:1});q('#locate').onclick=()=>m.locate({sheet:'Water',cell_range:q('#range').value});q('#invalid').onclick=()=>m.locate({sheet:'Water',cell_range:'C121junk'});q('#linked').onclick=()=>m.showLinkedBlocks();
const a={id:'A',text:'Duplicate passage wording',type:'text'},b={id:'B',text:'Duplicate passage wording',type:'text'},c={id:'C',text:'Added source passage',type:'text'};
q('#versions').innerHTML=versionComparison({blocks:[a,b],checked_scope:['page:1'],association_reviewed:true},{blocks:[b,a,c],checked_scope:[],association_reviewed:false},[{id:'page:1',label:'First saved page'}]);
const merged={rows:[['Heading spanning two columns',''],['Left','Right']],merges:[{row:0,col:0,rowspan:1,colspan:2}],notes:['Preserved original note']},contradictory={...structuredClone(merged),rows:[['Heading spanning two columns','Stored covered text'],['Left','Right']]};q('#tables').innerHTML='<h3>Valid recorded merge</h3>'+tableComparisonMarkup(merged)+'<h3>Contradictory merge retains stored grid</h3>'+tableComparisonMarkup(contradictory);
const page={id:'page-block',type:'text',text:'This passage originates on PDF page 3.',source_refs:[{page_index:2}]};q('#pages').innerHTML=blockComparisonMarkup(page)+orderMarkup(['page-block'],{'page-block':page});
await m.loadReader({sheet:'Water',row:1,column:1});window.fixture={m,requests};
