import {showPackageDownload} from './package-download.js';
import {valueMarkup} from './collaboration.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function receiptMarkup(entry,items=[]){
 const r=entry.receipt||entry,material=r.material||{},inspection=r.result?.inspection||{},item=items.find(i=>i.id===r.item_id)||{};
 const source=material.source?.source_id||r.source_receipt?.source_id||item.base?.source_id||'Not recorded';
 const title=material.title||inspection.title||item.proposal?.title||item.base?.source_title||item.base?.title||'Adoption receipt';
 const review=material.content_status?words(material.content_status):'Not recorded in this receipt';
 const status=r.choice==='current'?'Kept current':words(r.status)||'Not recorded';
 const fields=[['Material / task',title],['Source',source],['Contributor',r.contributor||item.actor||'Not recorded'],['Adopted by',r.actor||'Not recorded'],['Master revision',material.revision??'Not recorded'],['Recorded at',r.at||'Not recorded'],['Adoption decision',status],['Content review at receipt',review]];
 if(inspection.archive_revision!=null)fields.push(['Checked archive revision',inspection.archive_revision]);
 if(inspection.status)fields.push(['Spot-check status',words(inspection.status)]);
 return `<article class="collab-submission"><h3>${esc(title)}</h3><dl class="collab-values">${fields.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${valueMarkup(value)}</dd></div>`).join('')}</dl><p>Adoption and content review are separate. This receipt records a past decision; it does not update personal work.</p><details><summary>Original receipt details</summary><pre class="collab-value">${esc(JSON.stringify(entry,null,2))}</pre></details></article>`;
}
export function receiptsMarkup(receipts=[],items=[]){return receipts.map(r=>receiptMarkup(r,items)).join('')||'<p>No adoption receipts recorded.</p>';}
export class SubmissionDrawer {
 constructor(w){this.w=w;}
 async open(kind='submission'){
  const data=await this.w.api('/api/collaboration/collection-catalogue?kind='+kind);
  this.w.dialog(`<h2>${kind==='work'?'Distribute selected work':kind==='receipt'?'Return adoption receipts':'My submissions'}</h2><p>${kind==='receipt'?'Select the recorded decisions to return to contributors. Receipts do not alter their saved work.':kind==='work'?'Select sources, source tasks and archived material checks. Originals and common versions are included.':'Select saved source reviews, material drafts and inspection results. Download freezes each selected result; later editing cannot change the package.'}</p>${(data.assignment_changes||[]).map(i=>`<p role="status">${esc(i.task?.title||i.task?.id)}: ${esc(i.message)}</p>`).join('')}<div class="submission-choices">${data.items.map((i,n)=>`<label class="mw-check"><input type="checkbox" data-item-index="${n}"><span>${esc(i.title)}${i.revision!=null?' · saved revision '+i.revision:''}${i.status?' · '+esc(i.status):''}</span></label>`).join('')||'<p>No saved results available. Save progress in the source or material workspace first.</p>'}</div><label>Completed scope and remaining work<textarea id="bundle-summary" rows="3"></textarea></label><button id="bundle-download">Download selected ${kind==='work'?'work':'results'} as one package</button><p id="bundle-status" role="status"></p>${kind==='submission'?`<details><summary>Received adoption receipts</summary>${receiptsMarkup(data.received_receipts||[],data.inbox||[])}</details><details><summary>Frozen package history</summary>${(data.sent||[]).map(p=>`<article><p>${esc(p.at)} · ${p.items.length} items · ${esc(p.summary)}</p><button data-bundle-download="${esc(p.id)}">Download this saved package</button></article>`).join('')||'<p>No frozen packages yet.</p>'}</details>`:''}`,d=>{
   let pending=null;
   d.querySelector('#bundle-download').onclick=async()=>{const b=d.querySelector('#bundle-download');if(b.disabled)return;b.disabled=true;try{
    const items=[...d.querySelectorAll('[data-item-index]:checked')].map(n=>{const i=data.items[Number(n.dataset.itemIndex)];return {type:i.type,key:i.key};});if(!items.length)throw Error('Select at least one saved item.');const payload={kind,items,summary:d.querySelector('#bundle-summary').value},key=JSON.stringify(payload);if(pending?.key!==key)pending={key,id:crypto.randomUUID()};const result=await this.w.api.download('/api/collaboration/collection-export',{...payload,request_id:pending.id});showPackageDownload(d.querySelector('#bundle-status'),result,{frozen:true});
   }catch(e){d.querySelector('#bundle-status').textContent=e.message;}finally{b.disabled=false;}};
   d.querySelectorAll('[data-bundle-download]').forEach(b=>b.onclick=()=>this.w.api.download('/api/collaboration/collection-download',{id:b.dataset.bundleDownload}).then(result=>showPackageDownload(d.querySelector('#bundle-status'),result)).catch(e=>d.querySelector('#bundle-status').textContent=e.message));
  });
 }
 async inbox(){const data=await this.w.api('/api/collaboration/collection-catalogue');this.w.dialog(`<h2>Submitted tasks and inspections</h2><p>Each item has its own receipt. Apply related source decisions before material results. Incomplete or outdated items remain pending.</p>${(data.inbox||[]).map(i=>`<article><h3>${esc(i.proposal?.title||i.base?.source_title||i.base?.operation_id||i.id)}</h3><p>${esc(i.actor)} · ${esc(i.status)}</p><button data-bundle-item="${esc(i.id)}" ${i.status==='adopted'?'disabled':''}>Compare task result</button></article>`).join('')||'<p>No imported task results.</p>'}<button id="bundle-receipts">Download selected adoption receipts</button><details><summary>Per-item adoption receipts</summary>${receiptsMarkup(data.receipts||[],data.inbox||[])}</details>`,d=>{d.querySelector('#bundle-receipts').onclick=()=>this.open('receipt');d.querySelectorAll('[data-bundle-item]').forEach(b=>b.onclick=async()=>{try{await this.compare(b.dataset.bundleItem);}catch(e){this.w.message(e.message);}});});}
 async compare(id){const p=await this.w.api('/api/collaboration/collection-preview',{item_id:id});this.w.dialog(`<h2>Review task result</h2><p>${esc(p.item.actor)} · ${p.conflict?'Task changed since the shared starting version. Keep current or record a new task using this evidence.':'Current task matches the assigned starting version.'}</p><div class="collab-comparison"><section><h3>Current task</h3>${valueMarkup(p.current)}</section><section><h3>Submitted result</h3>${valueMarkup(p.proposed)}</section></div><details><summary>Shared starting version</summary>${valueMarkup(p.base)}</details><label class="mw-check"><input id="bundle-confirm" type="checkbox">I reviewed the scope, evidence and current task. Apply only this selected decision.</label><button data-bundle-choice="current">Keep current</button><button data-bundle-choice="incoming" ${p.conflict?'disabled':''}>Adopt submitted result</button><p id="bundle-adopt-status" role="status"></p>`,d=>{const ids={};d.querySelectorAll('[data-bundle-choice]').forEach(b=>b.onclick=async()=>{if(!d.querySelector('#bundle-confirm').checked)return;b.disabled=true;const choice=b.dataset.bundleChoice;try{ids[choice]||=crypto.randomUUID();const result=await this.w.api('/api/collaboration/collection-adopt',{item_id:id,expected_current_digest:p.current_digest,choice,explicit_confirmation:true,request_id:ids[choice]});d.querySelector('#bundle-adopt-status').textContent=result.status==='adopted'?'Selected decision recorded; the receipt preserves contributor and adopter.':'This item remains pending: '+(result.result?.message||result.status);}catch(e){d.querySelector('#bundle-adopt-status').textContent=e.message;}finally{b.disabled=false;}});});}
}
