import test from 'node:test';
import assert from 'node:assert/strict';
import {InterpretationEditor,checkingLogic,reviewReady,interpretationKeys} from '../frontend/components/interpretations.js';
import {designMarkup,emptyDesign} from '../frontend/components/check-design.js';
import {catalogOperators} from '../frontend/components/site-catalog.js';
const fields=()=>Object.fromEntries(interpretationKeys.map(k=>[k,{value:'',basis:'unresolved',references:[],gaps:[]}]));
function editor(api){const m={state:{actor:{id:'a'}},id:'m',api,q:()=>null,message:()=>{}};const e=new InterpretationEditor(m);e.journal=()=>true;e.active=e.key('u');e.drafts.set(e.active,{unit_id:'u',revision:0,fields:fields(),dirty:true,context:{fingerprint:'ctx',material_id:'m',requirement:{text:'Original'}}});return e;}
test('source absence permits reviewed extraction but leaves the checking gap and no verdict',()=>{const f=fields();f.condition={value:'',basis:'unresolved',state:'not_stated',absence_reason:'No explicit condition in this passage',references:[],gaps:[]};assert.equal(reviewReady(f.condition),true);const logic=checkingLogic(f);assert.match(logic.steps[1].description,/Not explicitly stated/);assert.ok(logic.gaps.includes('Condition'));assert.equal(logic.executable,false);assert.doesNotMatch(JSON.stringify(logic),/Satisfied|unconditionally/);});
test('unfinished interpretations remain in memory and block leaving without any background write',async()=>{const calls=[];const e=editor(async(...args)=>calls.push(args));let warned=false;e.m.unsavedDialog=()=>warned=true;e.changed();await e.persistWorking(e.active);assert.equal(calls.length,0);assert.equal(e.canLeave(),false);assert.equal(warned,true);assert.equal(e.needsRecovery(),true);assert.equal(e.draft.dirty,true);});
test('another reviewer cannot send a retained draft after identity switch',async()=>{let sent=false;const e=editor(async()=>{sent=true;});e.m.state.actor.id='b';await e.persistWorking(e.active);assert.equal(sent,false);});
test('configured field labels and only allowed comparisons replace raw mapping entry',()=>{const d=emptyDesign();d.groups.scope={id:'g',condition:'AND',rules:[{id:'r',field:'components.kind',type:'string',operator:'equal',value:'anchor',interpretation_field:'scope'}]};const html=designMarkup(d,'',{revision:1,fields:[{field:'components.kind',label:'Component kind',type:'string',operators:['equal']}]});assert.match(html,/Component kind/);assert.doesNotMatch(html,/placeholder="table.column"/);assert.doesNotMatch(html,/value="contains"/);assert.deepEqual(catalogOperators('boolean'),['equal','not_equal','in','not_in','is_null','is_not_null']);});
