import test from 'node:test';
import assert from 'node:assert/strict';
import {resizePair,minimumWorkspaceWidth} from '../frontend/components/pane-layout.js';
import {versionComparison,versionTextDiff} from '../frontend/components/version-comparison.js';
import {sourcePreview} from '../frontend/components/requirement-source.js';
test('dragging either side near zero snaps, normal movement preserves pair width and other panes',()=>{
 const widths=[300,400,350,500];assert.deepEqual(resizePair(widths,0,1,80),{widths:[380,320,350,500],collapse:null});assert.equal(resizePair(widths,0,1,-230).collapse,0);assert.equal(resizePair(widths,2,3,430).collapse,3);assert.deepEqual(widths,[300,400,350,500]);
});
test('workspace overflow accounts for each pane minimum, collapsed rails and visible separators',()=>{
 assert.equal(minimumWorkspaceWidth(),1261);
 assert.equal(minimumWorkspaceWidth(['original','content']),735);
 assert.equal(minimumWorkspaceWidth(['original','content','requirements']),452);
 assert.equal(minimumWorkspaceWidth(['original','content','requirements','interpretation']),176);
});
test('comparison hides unchanged passages and escapes source HTML while distinguishing additions and deletions',()=>{
 const shared={id:'same',text:'Unchanged',type:'text'},old={id:'x',text:'The fish is hot.',type:'text'},next={...old,text:'The fish is cold.'};const html=versionComparison({blocks:[shared,old]},{blocks:[shared,next]});assert.match(html,/1 changed passages/);assert.doesNotMatch(html,/Unchanged/);assert.match(html,/<del[^>]*>hot/);assert.match(html,/<ins[^>]*>cold/);assert.doesNotMatch(versionTextDiff('','<script>x</script>'),/<script>/);
});
test('long unchanged runs fold without losing their content',()=>{const html=versionTextDiff('x'.repeat(900)+' one','x'.repeat(900)+' two');assert.match(html,/unchanged characters/);assert.equal((html.match(/x/g)||[]).length,900);});
test('source overview preserves repeated Unicode text and nested relation colours',()=>{
 const text='鱼 shall check if warm and if cold';const d={text,units:{r:{conditions:[2,'a','b']},a:{},b:{}},spans:{r:[0,33],a:[14,21],b:[26,33]},field_spans:{r:{Subject:[0,1]},a:{'Main Verb':[3,7]}},labels:{r:'R1',a:'C1',b:'C2'}};
 const html=sourcePreview(d);assert.match(html,/semantic-0/);assert.match(html,/semantic-4/);assert.match(html,/annotation-outer/);assert.match(html,/C1 in R1/);assert.match(html,/C2 in R1/);
});

test('version comparison exposes relative surviving moves beside additions and removals without inventing index shifts',()=>{
 const blocks=ids=>ids.split('').map(id=>({id,text:'Same wording',type:'text'}));
 for(const [before,after]of [['AB','BAC'],['ABC','CA']]){const html=versionComparison({blocks:blocks(before)},{blocks:blocks(after)});assert.match(html,/Passage order changed/);assert.match(html,/Relative order of surviving passages/);assert.match(html,/Same wording <small>\(A\)/);assert.match(html,/(Added|Removed) passage/);}
 const onlyInsertion=versionComparison({blocks:blocks('AB')},{blocks:blocks('ACB')});assert.doesNotMatch(onlyInsertion,/Passage order changed/);assert.match(onlyInsertion,/Added passage/);
});
test('version comparison separates exact human review declarations from identical content',()=>{
 const blocks=[{id:'a',text:'Identical'}],saved={blocks,checked_scope:['page:1'],association_reviewed:true},local={blocks,checked_scope:[],association_reviewed:false},before=structuredClone({saved,local});
 const html=versionComparison(saved,local,[{id:'page:1',label:'First original page'}]);assert.match(html,/Human review declarations differ/);assert.match(html,/First original page \(page:1\)/);assert.match(html,/None recorded/);assert.match(html,/Not recorded as complete/);assert.match(html,/contents and order are identical/);assert.deepEqual({saved,local},before);assert.doesNotMatch(versionComparison(saved,structuredClone(saved)),/Human review declarations differ/);
});

import {Materials} from '../frontend/components/materials.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function control(){return {dataset:{},style:{},isConnected:true,disabled:false,hidden:false,tabIndex:0,children:[],attributes:{},innerHTML:'',textContent:'',classList:{toggle(){}},focus(){this.focused=true;this.onfocus?.();},scrollIntoView(){this.scrolled=true;},setAttribute(k,v){this.attributes[k]=v;},setCustomValidity(v){this.validationMessage=v;},reportValidity(){},querySelectorAll(){return [];},querySelector(){return null;},closest(){return null;}};}
function simpleMaterial(){const m=new Materials();m.id='A';m.token={};m.state={actor:{id:'reviewer'}};m.material={id:'A',revision:8,issues:[]};m.draft={blocks:[{id:'b',text:'Current'}],issues:[],checked_scope:[],association_reviewed:false};m.dirty=false;m.listVisible=false;m.readerView=()=> 'personal';m.collaboration={readonly:false};m.message=(message,kind)=>m.lastMessage={message,kind};m.changed=()=>m.dirty=true;m.renderMaterial=()=>{};return m;}

test('save shortcut always uses whole-page save and respects guards',async()=>{const m=simpleMaterial(),calls=[];m.q=()=>null;m.inspections={selected:null};m.save=()=>calls.push('page');const event=selector=>({key:'S',metaKey:true,preventDefault(){this.defaultPrevented=true;},target:{closest:s=>s===selector?{}:null}});await m.saveFromKeyboard(event('.mw-requirements'));await m.saveFromKeyboard(event('.mw-interpretation'));await m.saveFromKeyboard(event(null));assert.deepEqual(calls,['page','page','page']);await m.saveFromKeyboard({...event(null),isComposing:true});await m.saveFromKeyboard({...event(null),defaultPrevented:true});m.q=()=>({open:true});await m.saveFromKeyboard(event(null));assert.equal(calls.length,3);m.q=()=>null;m.collaboration.readonly=true;await m.saveFromKeyboard(event(null));assert.equal(calls.length,3);});

test('explicit content and original navigation reveal only their recorded pane and focus a destination',async()=>{const m=simpleMaterial(),nodes=new Map();m.q=s=>{if(!nodes.has(s))nodes.set(s,control());return nodes.get(s);};m.collapsedPanes=['original','content','requirements'];m.applyPaneWidths=()=>{};m.renderContent=()=>{};m.jumpToBlock(0);assert.deepEqual(m.collapsedPanes,['original','requirements']);assert.equal(m.q('[data-block="b"]').focused,true);m.loadReader=async()=>{m.reader={kind:'pdf'};return true;};await m.locate({page:2});assert.deepEqual(m.collapsedPanes,['requirements']);const before=[...m.collapsedPanes];await m.locate({page:0});assert.deepEqual(m.collapsedPanes,before);});

test('reading mode anchors the same stable block after preceding changes grow',()=>{const m=simpleMaterial(),host=control(),bounds={top:100,bottom:500},a=control(),b=control();host.scrollTop=1000;host.getBoundingClientRect=()=>bounds;a.dataset.block='b';a.getBoundingClientRect=()=>({top:120,bottom:300});b.dataset.block='b';b.getBoundingClientRect=()=>({top:820,bottom:1000});let rendered=false;host.querySelectorAll=()=>rendered?[b]:[a];m.q=()=>host;m.notebook={mode:'current'};m.renderContent=()=>rendered=true;const draft=JSON.stringify(m.draft);m.changeReadingMode('changes');assert.equal(host.scrollTop,1700);assert.equal(JSON.stringify(m.draft),draft);assert.equal(m.dirty,false);assert.equal(m.notebook.showChanges,true);});

test('original worksheet has one roving entry and leaves Formula Enter native',()=>{const m=simpleMaterial(),cells=Array.from({length:400},(_,i)=>{const c=control(),summary=control();c.dataset.originalCell=String.fromCharCode(65+i%10)+(1+Math.floor(i/10));c.querySelectorAll=()=>[summary];c.summary=summary;return c;});m.root={querySelectorAll:()=>cells};let linked=0;m.showLinkedBlocks=()=>linked++;m.bindOriginalCells();assert.equal(cells.filter(c=>c.tabIndex===0).length,1);assert.equal(cells.filter(c=>c.summary.tabIndex===0).length,1);cells[0].onkeydown({key:'ArrowDown',target:cells[0],preventDefault(){}});assert.equal(cells[10].focused,true);assert.equal(cells[10].tabIndex,0);assert.equal(cells[0].summary.tabIndex,-1);cells[10].onkeydown({key:'Enter',target:cells[10].summary,preventDefault(){throw Error('Native formula intercepted');}});assert.equal(linked,0);cells[10].onkeydown({key:'Enter',target:cells[10],preventDefault(){}});assert.equal(linked,1);assert.equal(m.selectedCell,'A2');m.bindOriginalCells();assert.equal(cells[10].tabIndex,0);});

function historyFixture(){const m=simpleMaterial(),nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,control());return nodes.get(s);};m.q=get;m.readonlyBlocks=blocks=>JSON.stringify(blocks);m.fromMaterial=historical=>structuredClone({blocks:historical.blocks||[],issues:historical.issues||[],checked_scope:historical.checked_scope||[],association_reviewed:true});m.dialog=(html,bind)=>{m.markup=html;const d=control();d.open=true;d.close=()=>d.open=false;d.querySelector=get;d.querySelectorAll=s=>s==='[data-restore-history]'?[get('restore')]:s==='[data-load-history]'?[get('read')]:s==='[data-history-page]'?[get('page')]:[];get('.mw-history').identity=Math.random();get('restore').dataset.restoreHistory='4';get('read').dataset.loadHistory='4';get('read').parentElement=get('read-parent');get('page').dataset.historyPage='20';m.dialogNode=d;bind(d);};return {m,get};}

test('late history for material A cannot open or issue version requests for B',async()=>{const {m}=historyFixture(),d=deferred(),calls=[];m.api=path=>{calls.push(path);return d.promise;};const pending=m.historyDialog();m.id='B';d.resolve({revisions:[{revision:4}],total:1});await pending;assert.equal(m.dialogNode,undefined);assert.match(calls[0],/id=A/);});

test('history restore is bound to exact original identity and ignores closed or newly edited drafts',async()=>{for(const change of ['close','navigate','edit']){const {m,get}=historyFixture(),d=deferred(),calls=[];m.api=async path=>{calls.push(path);return path.includes('/history?')?{revisions:[{revision:4}],total:1}:d.promise;};await m.historyDialog();const old=m.draft,pending=get('restore').onclick();if(change==='close')m.dialogNode.close();if(change==='navigate')m.id='B';if(change==='edit'){m.draft.blocks[0].text='New local edit';m.dirty=true;}d.resolve({material:{id:'A',revision:4,blocks:[{id:'old',text:'Historical'}]}});await pending;assert.equal(m.draft,old);assert.match(calls[1],/id=A&revision=4/);assert.doesNotMatch(calls[1],/id=B/);}});

test('same material history restore creates an unconfirmed local draft without saving',async()=>{const {m,get}=historyFixture(),calls=[];m.api=async path=>{calls.push(path);return path.includes('/history?')?{revisions:[{revision:4}],total:1}:{material:{id:'A',revision:4,blocks:[{id:'old',text:'Historical'}],checked_scope:['page:1'],confirmation:{actor:'Prior'}}};};await m.historyDialog();await get('restore').onclick();assert.equal(m.draft.blocks[0].text,'Historical');assert.equal(m.draft.blocks[0].restored_from_revision,4);assert.deepEqual(m.draft.checked_scope,[]);assert.equal(m.draft.association_reviewed,false);assert.equal(m.dirty,true);assert.equal(calls.length,2);assert.equal(m.dialogNode.open,false);});

test('failed history paging retains current page and retries without closing the dialog',async()=>{const {m,get}=historyFixture();let calls=0;m.api=async()=>{if(++calls===2)throw Error('offline');return {revisions:[{revision:4}],has_more:true,total:30};};await m.historyDialog();const d=m.dialogNode,markup=m.markup;await get('page').onclick();assert.equal(m.dialogNode,d);assert.equal(d.open,true);assert.equal(m.markup,markup);assert.match(get('#mw-history-status').textContent,/retry the same page/);await get('page').onclick();assert.equal(calls,3);});

test('region numeric editing preserves incomplete input and last valid preview until explicit valid Use',async()=>{const m=simpleMaterial(),block=m.draft.blocks[0];block.source_refs=[{page:1}];const nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,control());return nodes.get(s);},fields=['x0','y0','x1','y1'].map(k=>Object.assign(control(),{dataset:{crop:k},value:''}));m.api=async()=>({image:'/synthetic-page.png'});m.renderContent=()=>{};m.dialog=(html,bind)=>{m.dialogNode={querySelector:get,querySelectorAll:()=>fields,close(){this.closed=true;}};get('.mw-region-canvas').querySelector=get;bind(m.dialogNode);};await m.selectImageRegion(block);const left=fields[0],right=fields[2],overlay=get('.mw-region-selection'),last=overlay.style.cssText;left.value='';left.oninput();assert.equal(left.value,'');assert.equal(overlay.style.cssText,last);get('#mw-use-region').onclick();assert.equal(block.image,undefined);assert.equal(left.focused,true);left.value='12.';left.oninput();assert.equal(left.value,'12.');left.value='12.375';left.oninput();right.value='11';right.oninput();get('#mw-use-region').onclick();assert.equal(block.image,undefined);assert.equal(right.value,'11');right.value='88.125';right.oninput();get('#mw-use-region').onclick();assert.equal(block.image.source_ref.region.x0,12.375);assert.equal(block.image.source_ref.region.x1,88.125);assert.equal(m.dirty,true);assert.equal(m.dialogNode.closed,true);});

test('tools escape and outside pointer close only transient tools and preserve invalid input context',async()=>{const saved=globalThis.window,doc=globalThis.document,listeners=new Map(),m=simpleMaterial(),popover=control(),summary=control(),target=control();globalThis.window={addEventListener:(k,f)=>listeners.set(k,f),removeEventListener:k=>listeners.delete(k)};globalThis.document={activeElement:target};popover.open=true;popover.querySelector=s=>s==='summary'?summary:null;popover.contains=n=>n===target;target.closest=()=>popover;m.root={querySelectorAll:()=>[popover]};m.q=()=>null;try{m.bindTools();let prevented=false;m.root.onkeydown({key:'Escape',target,preventDefault(){prevented=true;},stopPropagation(){}});assert.equal(prevented,true);assert.equal(popover.open,false);assert.equal(summary.focused,true);popover.open=true;listeners.get('pointerdown')({target:{}});assert.equal(popover.open,false);popover.open=true;m.action=async()=>{};popover.querySelector=s=>s.includes('invalid')?{}:summary;await m.toolAction('reader-cells',target);assert.equal(popover.open,true);popover.querySelector=s=>s==='summary'?summary:null;await m.toolAction('reader-linked',target);assert.equal(popover.open,false);}finally{globalThis.window=saved;globalThis.document=doc;}});

test('keyboard separator collapse focuses the newly visible rail for immediate restoration',()=>{for(const key of ['Home','End','ArrowLeft']){const m=simpleMaterial(),names=['original','content','requirements','interpretation'],panes=names.map(()=>control()),handle=control();m.collapsedPanes=[];m.paneWeights=[1,1,1,1];panes.forEach(p=>p.getBoundingClientRect=()=>({width:key==='ArrowLeft'?70:300}));m.q=s=>panes[names.indexOf(s.slice(4))];m.root={querySelectorAll:()=>[handle]};m.applyPaneWidths=()=>handle.hidden=m.collapsedPanes.length>0;m.wireResize();handle.onkeydown({key,preventDefault(){}});const name=key==='End'?'content':'original',pane=panes[names.indexOf(name)];assert.equal(pane.focused,true);assert(m.collapsedPanes.includes(name));pane.onkeydown({key:'Enter',target:pane,preventDefault(){}});assert(!m.collapsedPanes.includes(name));}});

test('reading anchor clamps a shortened block so the same passage stays visible',()=>{const m=simpleMaterial(),host=control(),old=control(),current=control();host.scrollTop=1000;host.getBoundingClientRect=()=>({top:100,bottom:600});old.dataset.block=current.dataset.block='b';old.getBoundingClientRect=()=>({top:-500,bottom:800});current.getBoundingClientRect=()=>({top:200,bottom:300});let changed=false;host.querySelectorAll=()=>changed?[current]:[old];m.q=()=>host;m.notebook={};m.renderContent=()=>changed=true;m.changeReadingMode('current');assert.equal(host.scrollTop,1168);});
