import test from 'node:test';
import assert from 'node:assert/strict';
import {searchBlocks,tableWindow,regionFromPoints,refsForLocation,claimDraftOwner} from '../frontend/components/material-navigation.js';
import {Materials,materialStatus} from '../frontend/components/materials.js';
import {runtimeMarkup} from '../frontend/components/runtime-status.js';
test('search covers all blocks, hidden table windows and notes',()=>{const blocks=Array.from({length:100},(_,i)=>({id:String(i),text:'paragraph'}));blocks[83]={type:'table',table:{rows:Array.from({length:90},(_,i)=>['cell',i===89?'Hidden Needle':'']),notes:['Note Match']}};assert.deepEqual(searchBlocks(blocks,'hidden needle'),[83]);assert.deepEqual(searchBlocks(blocks,'note match'),[83]);assert.equal(searchBlocks(blocks,'').length,100);assert.deepEqual(searchBlocks(blocks,'missing'),[]);});
test('table windows are bounded but do not mutate data and use absolute coordinates',()=>{const x=new Materials();const table={rows:Array.from({length:200},(_,r)=>Array.from({length:30},(_,c)=>`${r},${c}`)),merges:[],notes:[]};x.tableWindows.a={row:80,column:20};const before=JSON.stringify(table),html=x.tableMarkup({id:'a',table});assert.equal((html.match(/data-cell=/g)||[]).length,400);assert.match(html,/data-cell="80,20"/);assert.match(html,/data-cell="119,29"/);assert.doesNotMatch(html,/data-cell="0,0"/);assert.equal(JSON.stringify(table),before);assert.deepEqual(tableWindow(table,{row:999,column:-4}),{row:199,column:0,endRow:200,endColumn:10,columns:30});});
test('personal content opens as rendered Markdown cells and archived content cannot enter editing',()=>{const x=new Materials();const block={id:'a',type:'text',text:'Read <this>',source_refs:[]};x.draft={blocks:[block]};x.material={scope:[]};assert.match(x.blockMarkup(block,0),/Read &lt;this&gt;/);assert.doesNotMatch(x.blockMarkup(block,0),/<textarea|Hierarchy and block type/);x.notebook.editing='a';assert.match(x.blockMarkup(block,0),/<textarea/);x.material.collaboration={view:'archive'};assert.doesNotMatch(x.blockMarkup(block,0),/<textarea/);});
test('drag region is reverse-safe, bounded and rejects empty drag',()=>{const rect={left:10,top:20,width:200,height:400};assert.deepEqual(regionFromPoints({x:170,y:340},{x:50,y:100},rect),{x0:20,y0:20,x1:80,y1:80});assert.deepEqual(regionFromPoints({x:-20,y:0},{x:400,y:900},rect),{x0:0,y0:0,x1:100,y1:100});assert.equal(regionFromPoints({x:50,y:100},{x:50,y:100},rect),null);});
test('original associations match exact pages, intersecting cells and known HTML anchors only',()=>{const blocks=[{source_refs:[{page:2}]},{source_refs:[{page_index:1}]},{source_refs:[{sheet:'Water',cell_range:'B2:D7'}]},{source_refs:[{anchor:'stable-one',locator:'/body/p[4]'}]}];assert.deepEqual(refsForLocation(blocks,{page:2}),[0,1]);assert.deepEqual(refsForLocation(blocks,{sheet:'Water',cell_range:'C3'}),[2]);assert.deepEqual(refsForLocation(blocks,{sheet:'Other',cell_range:'C3'}),[]);assert.deepEqual(refsForLocation(blocks,{anchor:'stable-one'}),[3]);assert.deepEqual(refsForLocation(blocks,{anchor:'similar-but-unknown'}),[]);});
test('saving changed body delegates scope retention to server and keeps no client approval',async()=>{const x=new Materials();x.id='a';x.draft={blocks:[{id:'a',text:'Changed'}],checked_scope:['page:1'],association_reviewed:true};x.bodyChanged=true;let sent;x.mutate=async(path,body)=>sent={path,body};await x.save();assert.equal(sent.path,'/api/material/save');assert.equal('checked_scope' in sent.body,false);assert.equal('association_reviewed' in sent.body,false);assert.deepEqual(x.draft.checked_scope,['page:1']);});
test('candidate summary count is truthful without loading body',()=>{const result=materialStatus({candidates:[{status:'ready',block_count:6000}]});assert.match(result.processing,/6000 blocks/);});
test('runtime state errors escape content and distinguish saved error history',()=>{const html=runtimeMarkup({checked_at:'now',components:[{name:'Material extraction',state:'idle',last_success:'today',last_error:{message:'<script>old</script>',event_id:'ref'}}]});assert.match(html,/Previous failure retained/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);assert.match(html,/does not certify content quality/);});
test('review impact discloses retained check provenance and never claims final confirmation',()=>{const x=new Materials();x.material={scope:[{id:'page:1',label:'Page 1'},{id:'page:2',label:'Page 2'}],review_impact:{affected_scope:['page:1'],retained_scope:['page:2']},review_checks:{'page:2':{actor:'Reviewer',at:'today',content_revision:6}}};const html=x.reviewImpactMarkup();assert.match(html,/Page 1/);assert.match(html,/Reviewer/);assert.match(html,/content revision 6/);assert.match(html,/do not restore final confirmation/);});
test('read-only history and comparisons paginate full blocks and table cells',()=>{const x=new Materials(),rows=Array.from({length:1000},()=>Array(30).fill('cell'));const html=x.readonlyBlocks(Array.from({length:60},(_,i)=>({id:String(i),type:'text',text:String(i)})));assert.equal((html.match(/class="mw-readonly-block"/g)||[]).length,40);assert.match(html,/Next blocks/);const table=x.readonlyTable({rows,notes:[]});assert.equal((table.match(/<td>/g)||[]).length,400);assert.match(table,/1000/);assert.match(table,/readonly-table-down/);});
test('compact candidates disclose additional warnings and full comparison keeps all warnings',async()=>{const x=new Materials();x.id='fixture';x.token={};x.material={candidates:[{id:'c',status:'ready',warning_count:6,warnings:['one','two','three'],block_count:4}]};assert.match(x.candidatesMarkup(),/3 additional warnings/);x.draft={blocks:[]};x.api=async()=>({id:'c',complete:true,warnings:['one','two','three','four','five','six'],blocks:[]});x.dialog=html=>x.dialogHTML=html;await x.candidateDialog('c');assert.match(x.dialogHTML,/All candidate warnings \(6\)/);assert.match(x.dialogHTML,/>six</);});
test('shared formula followers show known anchor without inventing an equals expression',()=>{const x=new Materials();const html=x.excelRows({row:2,cells:[[{address:'B2',formula_present:true,formula:null,formula_anchor:'B1',formula_reference:'B1:B9',formula_note:'Shared formula follower; expression stored at anchor.',cached:'12'}]]});assert.match(html,/Formula anchor: B1/);assert.match(html,/Formula range: B1:B9/);assert.match(html,/Saved value: 12/);assert.doesNotMatch(html,/<code>=<\/code>/);});

test('copied sessionStorage gets a distinct live journal owner while reload reclaims its own',async()=>{const held=new Set();const locks={request:async(name,options,callback)=>{const taken=held.has(name);if(!taken)held.add(name);return callback(taken?null:{name});}};const store=initial=>({value:initial,getItem(){return this.value;},setItem(key,value){this.value=value;}});const a=store('inherited'),b=store('inherited');const ownerA=await claimDraftOwner(a,locks,()=> 'new-a'),ownerB=await claimDraftOwner(b,locks,()=> 'new-b');assert.equal(ownerA.id,'inherited');assert.equal(ownerB.id,'new-b');assert.equal(b.value,'new-b');held.delete('material-draft-owner:'+ownerA.id);const reloadA=await claimDraftOwner(a,locks,()=> 'unwanted');assert.equal(reloadA.id,ownerA.id);assert.equal(held.has('material-draft-owner:'+ownerB.id),true);});
test('unsupported or rejected Web Locks never reuse a writable journal owner',async()=>{const store={value:'old-owner',getItem(){return this.value;},setItem(key,value){this.value=value;}};const first=await claimDraftOwner(store,null,()=> 'fresh-a');assert.deepEqual(first,{id:'fresh-a',recoveryOwner:'old-owner'});const second=await claimDraftOwner(store,{request:()=>Promise.reject(Error('Unavailable'))},()=> 'fresh-b');assert.deepEqual(second,{id:'fresh-b',recoveryOwner:'old-owner'});assert.equal(store.value,'old-owner');});

test('leaving the initial unmounted workspace safely clears focus mode',()=>{const m=new Materials();assert.doesNotThrow(()=>m.leave());assert.equal(m.focusMode,false);});

test('dismissing review notice is presentation only and changed impact returns',async()=>{
 const x=new Materials(),host={innerHTML:''};x.q=()=>host;x.id='material';x.draft={blocks:[{id:'b',text:'Body'}],checked_scope:[]};x.material={content_revision:2,scope:[],review_impact:{affected_scope:['html'],retained_scope:[]}};
 const before=JSON.stringify([x.material,x.draft]);x.renderSystemNotices();assert.match(host.innerHTML,/Dismiss review notification/);
 await x.action('dismiss-review-notice',{});assert.equal(host.innerHTML,'');x.renderSystemNotices();assert.equal(host.innerHTML,'');assert.equal(JSON.stringify([x.material,x.draft]),before);
 x.material.content_revision=3;x.renderSystemNotices();assert.match(host.innerHTML,/Dismiss review notification/);
});

test('document context escapes source text and disclosure state is material scoped',()=>{
 const x=new Materials();x.id='one';x.material={scope:[{id:'html:document'}]};x.draft={blocks:[{id:'body',text:'Body'}]};x.reader={document_information:{title:{value:'<img src=x onerror=bad()>'},fields:[{label:'<label>',value:'<script>bad()</script>'}]}};
 assert.doesNotMatch(x.documentInformationMarkup(),/<img|<script>/);assert.match(x.documentInformationMarkup(),/&lt;script&gt;/);
 x.root={querySelectorAll:()=>[{dataset:{disclosureKey:x.disclosureKey('document-information')},open:false}]};x.captureDisclosures();assert.doesNotMatch(x.disclosureAttributes('document-information'),/ open$/);
 x.id='two';assert.match(x.disclosureAttributes('document-information'),/ open$/);
});

 test('document context appears only after extraction and editing creates a source-bound draft',async()=>{
 const x=new Materials();x.id='a';x.material={source:{content_hash:'hash'},scope:[{id:'html:document'}],candidates:[]};x.draft={blocks:[]};x.reader={document_information:{title:{value:'Source title',locator:'html > h1',anchor:'original-title'},fields:[]}};
 assert.equal(x.documentInformationMarkup(),'');x.material.candidates=[{status:'running'}];assert.equal(x.documentInformationMarkup(),'');x.material.candidates=[{status:'ready'}];assert.match(x.documentInformationMarkup(),/Source title/);assert.equal(x.draft.blocks.length,0);
 let edited;x.changed=()=>{x.dirty=true};x.notebook.edit=id=>edited=id;await x.action('edit-document-information',{});assert.equal(x.draft.blocks[0].role,'document_information');assert.equal(edited,x.draft.blocks[0].id);assert.equal(x.draft.blocks[0].source_refs[0].scope_id,'html:document');assert.equal(x.dirty,true);
 });

test('only the latest extraction is displayed while earlier records remain unchanged',()=>{
 const x=new Materials();x.id='m';x.draft={blocks:[{id:'b'}]};x.material={candidates:[{id:'first',status:'ready',block_count:342,started_at:'2026-09-15T12:08:07Z'},{id:'second',status:'ready',block_count:342,started_at:'2026-09-15T12:39:25Z'}]};
 const before=JSON.stringify(x.material),markup=x.candidatesMarkup();
 assert.equal((markup.match(/class="mw-candidate"/g)||[]).length,1);assert.doesNotMatch(markup,/Earlier extractions|data-id="first"/);assert.match(markup,/data-id="second"/);assert.equal(JSON.stringify(x.material),before);
 x.material.candidates[1].status='failed';const failed=x.candidatesMarkup();assert.match(failed,/Extraction failed/);assert.doesNotMatch(failed,/data-id="first"/);assert.doesNotMatch(failed,/data-action="compare-candidate" data-id="second"/);x.material.candidates[1].status='merged';assert.equal(x.candidatesMarkup(),'');
});
