import test from 'node:test';
import assert from 'node:assert/strict';
import {Materials} from '../frontend/components/materials.js';
function peer(){const m=new Materials();m.state={collaboration:{peer_sync:true}};m.material={};m.reviewReady=()=>true;m.dirty=true;m.message=()=>{};m.collaboration.runPreview=()=>{throw Error('Unexpected administrator preview');};return m;}
test('peer archive saves declarations before opening explicit confirmation',async()=>{const m=peer(),calls=[];m.save=async()=>{calls.push('save');m.dirty=false;return true;};m.reviewDialog=()=>calls.push('confirm');await m.archiveContent();assert.deepEqual(calls,['save','confirm']);});
test('peer archive stops after failed save',async()=>{const m=peer();m.save=async()=>false;m.reviewDialog=()=>{throw Error('Unsaved confirmation');};await m.archiveContent();assert.equal(m.dirty,true);});
test('peer archive requires fresh declarations after saved content changes',async()=>{const m=peer();m.save=async()=>{m.dirty=false;m.reviewReady=()=>false;return true;};m.reviewDialog=()=>{throw Error('Invalidated review');};await m.archiveContent();});

import {installGlobalSettings,assigneeOptions,automationResultMarkup,aiKeyConflict} from '../frontend/components/global-settings.js';
import {catalogSettings,catalogIssue} from '../frontend/components/site-catalog.js';
import {settings} from '../frontend/components/extraction.js';
import {settingsOperation,settingsPending,settingsFailure} from '../frontend/components/settings-form.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const tick=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function control(value=''){return {value,checked:false,disabled:false,dataset:{},textContent:'',innerHTML:'',children:[],attributes:{},isConnected:true,focus(){this.focused=true;},setCustomValidity(v){this.validationMessage=v;},reportValidity(){},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];},addEventListener(k,fn){(this.listeners??={})[k]=fn;},appendChild(n){this.children.push(n);},querySelectorAll(){return [];}};}
function feedback(){const host=control(),choices=['saved','local'].map(value=>({...control(),dataset:{settingsVersion:value}}));host.ownerDocument={createElement:()=>control()};host.querySelectorAll=()=>choices;return host;}
const changed=message=>Object.assign(Error(message),{definitive:true});
const aiData=()=>({revision:2,endpoint:'https://example.invalid/v1/chat/completions',model:'saved',has_key:true,enabled:false,max_bytes:5000,status:'Disabled'});
function globalFixture(api){
 const prior={document:globalThis.document,window:globalThis.window},nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,s.endsWith('feedback')?feedback():control());return nodes.get(s);};
 const dialog=get('#global-settings-dialog');dialog.querySelector=get;dialog.contains=()=>true;dialog.showModal=()=>dialog.open=true;dialog.close=()=>dialog.open=false;
 const ai=get('#ai-settings-form');ai.elements=Object.fromEntries(Object.entries({endpoint:'https://example.invalid/v1/chat/completions',model:'local',api_key:'',clear_key:'',enabled:'',max_bytes:'6000'}).map(([k,v])=>[k,control(v)]));ai.querySelectorAll=()=>Object.values(ai.elements);
 const schedule=get('#automation-form');schedule.elements=Object.fromEntries(Object.entries({interval_days:'7',sample_size:'5',assignee:'Absent reviewer',timezone:'UTC',enabled:''}).map(([k,v])=>[k,control(v)]));schedule.querySelectorAll=()=>Object.values(schedule.elements);schedule.querySelector=()=>get('#schedule-fieldset');
 const policy=get('#policy-form');policy.elements=Object.fromEntries(['system1','content','requirement'].map(k=>[k,Object.assign(control('90'),{name:k})]));policy.querySelectorAll=()=>Object.values(policy.elements);
 const confidence=get('#confidence-settings');confidence.querySelector=get;confidence.querySelectorAll=()=>Object.values(policy.elements);
 dialog.querySelectorAll=selector=>selector==='input[type=password]'?[ai.elements.api_key]:[get('[data-settings-close]'),...(get('#settings-body').innerHTML.includes('ai-settings-form')?Object.values(ai.elements):[]),...(get('#settings-body').innerHTML.includes('automation-form')?[...Object.values(schedule.elements),...Object.values(policy.elements)]:[])];
 globalThis.document={querySelector:get,querySelectorAll:()=>[],addEventListener(){},activeElement:null};globalThis.window={dispatchEvent(){}};
 const installed=installGlobalSettings({api,getState:()=>({actors:[{name:'First reviewer'}],csrf:'synthetic'}),canLeave:()=>true,onSynced:()=>{},notice:()=>{}});
 return {get,ai,schedule,policy,dialog,installed,restore(){Object.assign(globalThis,prior);}};
}
const submit=form=>form.onsubmit({preventDefault(){},currentTarget:form});

test('pending form work freezes controls once and restores existing read-only state',async()=>{const fields=[control('exact'),Object.assign(control(),{disabled:true})],form={querySelectorAll:()=>fields},d=deferred();let calls=0;const work=()=>{calls++;return d.promise;};const first=settingsOperation(form,fn=>fn(),work);await settingsOperation(form,fn=>fn(),work);assert.equal(calls,1);assert.equal(settingsPending(form),true);assert(fields.every(n=>n.disabled));d.resolve();await first;assert.equal(fields[0].disabled,false);assert.equal(fields[1].disabled,true);assert.equal(settingsPending(form),false);});

test('API contradictory replacement and removal keeps the masked input and sends no write',async()=>{let writes=0;const f=globalFixture(async(_,body)=>{if(body)writes++;return aiData();});try{f.get('#open-ai-settings').onclick();await tick();f.ai.elements.api_key.value='do-not-render-secret';f.ai.elements.clear_key.checked=true;await submit(f.ai);assert.equal(writes,0);assert.equal(f.ai.elements.api_key.value,'do-not-render-secret');assert.equal(f.ai.elements.clear_key.checked,true);assert.equal(f.ai.elements.api_key.focused,true);assert.doesNotMatch(f.get('#ai-settings-feedback').textContent,/do-not-render-secret/);assert.equal(aiKeyConflict({api_key:'',clear_key:true}),false);}finally{f.restore();}});

test('API deferred save keeps one submitted payload and prevents Close, Escape and shell replacement',async()=>{const d=deferred(),calls=[];const f=globalFixture(async(path,body)=>{if(body){calls.push(body);return d.promise;}return aiData();});try{f.get('#open-ai-settings').onclick();await tick();f.ai.elements.api_key.value='exact-dummy-key';const save=submit(f.ai);await submit(f.ai);assert.equal(calls.length,1);assert.equal(calls[0].api_key,'exact-dummy-key');assert.equal(f.ai.elements.api_key.disabled,true);assert.equal(f.installed.isBusy(),true);f.get('[data-settings-close]').onclick();assert.equal(f.dialog.open,true);let prevented=false;f.dialog.listeners.cancel({preventDefault(){prevented=true;}});assert.equal(prevented,true);const html=f.dialog.innerHTML;f.get('#open-automation').onclick();assert.equal(f.dialog.innerHTML,html);d.reject(Error('synthetic unavailable'));await save;assert.equal(f.ai.elements.api_key.value,'exact-dummy-key');assert.equal(f.ai.elements.api_key.disabled,false);assert.equal(f.installed.isBusy(),false);assert.match(f.get('#ai-settings-feedback').textContent,/unavailable/);}finally{f.restore();}});

test('API changed revision compares nonsecret values then requires explicit new Save with retained key',async()=>{const calls=[];let reads=0;const f=globalFixture(async(_,body)=>{if(!body)return {...aiData(),revision:++reads===1?2:3,model:'remote'};calls.push(body);if(calls.length===1)throw changed('API settings changed in another window. Reopen Settings before saving.');return {...aiData(),revision:4};});try{f.get('#open-ai-settings').onclick();await tick();f.ai.elements.model.value='my model';f.ai.elements.api_key.value='sensitive-dummy-123';await submit(f.ai);const h=f.get('#ai-settings-feedback');assert.equal(reads,1);await h.children[0].onclick();assert.equal(reads,2);assert.match(h.innerHTML,/my model/);assert.match(h.innerHTML,/Replace saved key/);assert.doesNotMatch(h.innerHTML,/sensitive-dummy-123/);h.querySelectorAll()[1].onclick();assert.equal(calls.length,1);assert.equal(f.ai.elements.api_key.value,'sensitive-dummy-123');await submit(f.ai);assert.equal(calls[1].revision,3);assert.equal(calls[1].model,'my model');assert.equal(calls[1].api_key,'sensitive-dummy-123');assert.equal(f.ai.elements.api_key.value,'');}finally{f.restore();}});

test('settings revision comparison rejects changed proposal and uncertain errors never offer rebase',async()=>{const host=feedback();let text='one',accepted=0;const options={read:async()=>({revision:3}),local:()=>({text}),saved:x=>x,stamp:()=>text,useLocal:()=>accepted++,useSaved:()=>accepted++};settingsFailure(host,Error('API settings changed'),options);assert.equal(host.children.length,0);settingsFailure(host,changed('API settings changed'),options);await host.children[0].onclick();text='two';host.querySelectorAll()[1].onclick();assert.equal(accepted,0);assert.match(host.textContent,/proposal changed/);});

const field=(patch={})=>({field:'site.temperature',label:'Temperature',description:'Recorded temperature',type:'string',operators:['contains'],...patch});
function catalogFixture(api,run){const host=control(),form=control(),row=control(),inputs=Object.fromEntries(['field','label','description','type'].map(k=>[k,Object.assign(control(),{dataset:{catalog:k}})])),op=Object.assign(control(),{dataset:{operator:'equal'}}),details=control(),error=control(),message=feedback(),add=control();const map={'form':form,'[data-add-field]':add,'[data-catalog-message]':message,'[data-catalog-row="0"]':row};host.querySelector=s=>map[s];host.querySelectorAll=s=>s==='[data-catalog-row]'?[row]:[];row.dataset.catalogRow='0';row.querySelectorAll=s=>s==='[data-catalog]'?Object.values(inputs):s==='[data-operator]:checked'?(op.checked?[op]:[]):[op];row.querySelector=s=>s==='details'||s==='summary'?details:s==='[data-catalog-error]'?error:s==='[data-operator]'?op:inputs[s.match(/="(.*?)"/)[1]];form.querySelectorAll=()=>[...Object.values(inputs),op,add];return {host,form,row,inputs,op,details,error,message,add,mount:()=>catalogSettings(host,api,()=>{},run)};}

test('catalog incompatible type change keeps no implicit operator and locates empty comparisons',async()=>{let writes=0;const f=catalogFixture(async(_,body)=>{if(body)writes++;return {revision:1,fields:[field()]};});await f.mount();f.inputs.type.value='boolean';f.inputs.type.oninput();assert.match(f.host.innerHTML,/Removed incompatible comparisons: contains/);assert.match(f.host.innerHTML,/Allowed comparisons \(0\)/);await submit(f.form);assert.equal(writes,0);assert.equal(f.op.focused,true);assert.equal(f.details.open,true);assert.match(f.error.textContent,/Select at least one/);});

test('catalog validation keeps owner bounds, exact mappings, Unicode code points and empty catalogs',()=>{assert.equal(catalogIssue([]),null);assert.equal(catalogIssue([field({label:'😀'.repeat(2000)})]),null);assert.equal(catalogIssue([field({label:'😀'.repeat(2001)})]).key,'label');assert.equal(catalogIssue([field(),field()]).index,1);assert.equal(catalogIssue([field({field:' site.temperature'})]).key,'field');assert.equal(catalogIssue([field({field:'s.'+'t'.repeat(198)})]),null);assert.equal(catalogIssue([field({field:'s.'+'t'.repeat(199)})]).key,'field');assert.equal(catalogIssue([field({operators:[]})]).key,'operators');assert.equal(catalogIssue(Array.from({length:501},(_,i)=>field({field:'site.f'+i}))).index,500);});

test('catalog save uses shared guard, blocks structural redraw and retains proposal through revision recovery',async()=>{const calls=[],d=deferred();let reads=0,guards=0;const f=catalogFixture(async(_,body)=>{if(!body)return {revision:++reads===1?1:2,fields:[field({operators:['equal']})]};calls.push(body);if(calls.length===1)return d.promise;return {revision:3,fields:body.fields};},async fn=>{guards++;return fn();});await f.mount();f.inputs.label.value='My exact name';f.inputs.label.oninput();const save=submit(f.form);await submit(f.form);assert.equal(calls.length,1);assert.equal(f.add.disabled,true);const html=f.host.innerHTML;f.add.onclick();assert.equal(f.host.innerHTML,html);d.reject(changed('The catalog changed. Reload it before saving.'));await save;assert.equal(f.inputs.label.value,'My exact name');await f.message.children[0].onclick();f.message.querySelectorAll()[1].onclick();assert.equal(calls.length,1);await submit(f.form);assert.equal(calls[1].revision,2);assert.equal(calls[1].fields[0].label,'My exact name');assert(guards>=3);});

test('confidence conflict retains exact proposal and latest hidden policy field without automatic save',async()=>{const container=control(),form=control(),status=feedback(),inputs=['system1','content','requirement'].map(name=>Object.assign(control('91.25'),{name}));form.elements=Object.fromEntries(inputs.map(n=>[n.name,n]));form.querySelectorAll=()=>inputs;container.querySelector=s=>s==='#policy-form'?form:status;let reads=0;const calls=[];const api=async(_,body)=>{if(!body)return {policy:{revision:++reads===1?1:2,system1:.9,content:.9,requirement:.9,system3:reads===1?.3:.6},history:[]};calls.push(body);if(calls.length===1)throw changed('The settings changed. Reload before saving.');return {};};await settings(container,api);await submit(form);assert.equal(reads,1);await status.children[0].onclick();status.querySelectorAll()[1].onclick();assert.equal(calls.length,1);await submit(form);assert.equal(calls[1].revision,2);assert.equal(calls[1].values.system1,.9125);assert.equal(calls[1].values.system3,.6);});

test('standalone confidence deferred failure preserves inputs and prior disabled state',async()=>{const container=control(),form=control(),status=feedback(),input=Object.assign(control('93'),{name:'system1'}),d=deferred();form.querySelectorAll=()=>[input];container.querySelector=s=>s==='#policy-form'?form:status;let writes=0;await settings(container,async(_,body)=>{if(body){writes++;return d.promise;}return {policy:{revision:1,system1:.9,content:.9,requirement:.9,system3:.8},history:[]};});const save=submit(form);await submit(form);assert.equal(writes,1);assert.equal(input.disabled,true);d.reject(Error('offline'));await save;assert.equal(input.value,'93');assert.equal(input.disabled,false);assert.match(status.textContent,/offline/);});

test('schedule retained missing assignee and conflict are explicit, with no dispatch endpoint',async()=>{let reads=0;const calls=[];const data=()=>({revision:++reads===1?'one':'two',settings:{enabled:false,interval_days:7,sample_size:5,assignee:'Absent reviewer',timezone:'UTC'},can_schedule:true,can_edit_confidence:false,status:{status:'scheduled'}});const f=globalFixture(async(path,body)=>{if(path==='/api/settings')return {policy:{revision:1,system1:.9,content:.9,requirement:.9,system3:.8},history:[]};assert.equal(path,'/api/automation');if(!body)return data();calls.push(body);if(calls.length===1)throw changed('Automation settings changed. Reload before saving.');return {...data(),revision:'three'};});try{await f.installed.automation();assert.match(f.get('#settings-body').innerHTML,/value="Absent reviewer" selected/);f.schedule.elements.interval_days.value='11';await submit(f.schedule);const h=f.get('#automation-feedback');await h.children[0].onclick();h.querySelectorAll()[1].onclick();assert.equal(calls.length,1);await submit(f.schedule);assert.equal(calls[1].revision,'two');assert.equal(calls[1].settings.assignee,'Absent reviewer');assert.equal(calls[1].settings.interval_days,11);assert(Object.values(f.policy.elements).every(n=>n.disabled));}finally{f.restore();}});

test('failed collaboration file selection clears picker immediately and keeps prior comparison for same-file retry',async()=>{const original=globalThis.fetch,f=globalFixture(async()=>({})),d=deferred();let calls=0;globalThis.fetch=()=>{calls++;return d.promise;};try{await f.installed.collaboration();const input=f.get('#sync-file');input.files=[{name:'same.zip',size:40}];input.value='fakepath';f.get('#sync-result').innerHTML='Previous reviewed comparison';const importing=input.onchange();assert.equal(input.value,'');d.reject(Error('synthetic failure'));await importing;assert.match(f.get('#settings-feedback').textContent,/same.zip.*synthetic failure/);assert.equal(f.get('#sync-result').innerHTML,'Previous reviewed comparison');globalThis.fetch=async()=>{calls++;return {ok:false,json:async()=>({error:'Rejected again'})};};input.value='fakepath';await input.onchange();assert.equal(calls,2);assert.equal(input.value,'');input.files=[];await input.onchange();assert.equal(calls,2);}finally{globalThis.fetch=original;f.restore();}});

test('scheduler report distinguishes reported dispatch, task outcomes and missing evidence',()=>{assert.match(assigneeOptions([], 'Exact absent'),/value="Exact absent" selected/);assert.match(automationResultMarkup(null),/No dispatch result recorded/);const h=automationResultMarkup({status:'complete',at:'2026-09-20T10:00:00Z',assignee:'Earlier reviewer',requested_count:5,eligible_count:0,selected_count:0,items:[]});assert.match(h,/Task dispatch finished/);assert.match(h,/Selected: 0/);assert.match(h,/does not indicate completed human review/);assert.match(h,/Earlier reviewer/);assert.doesNotMatch(h,/All checks complete/);const mixed=automationResultMarkup({status:'complete',items:[{status:'created'},{status:'already_pending'},{status:'skipped',material_id:'M',reason:'archive changed'}]});assert.match(mixed,/Requested: Not recorded/);assert.match(mixed,/Created: 1 · Already pending: 1 · Skipped: 1/);assert.match(mixed,/archive changed/);assert.match(automationResultMarkup({status:'scheduled'}),/Waiting for scheduled time/);assert.match(automationResultMarkup({status:'disabled'}),/Scheduling disabled/);});

 test('catalog duplicate error clears when the other mapping is corrected before native resubmission',async()=>{let writes=0;const f=catalogFixture(async(_,body)=>{if(body){writes++;return {revision:2,fields:body.fields};}return {revision:1,fields:[field(),field()]};}),other=catalogFixture(()=>{});other.row.dataset.catalogRow='1';const originalQuery=f.host.querySelector;f.host.querySelector=s=>s==='[data-catalog-row="1"]'?other.row:originalQuery(s);f.host.querySelectorAll=s=>s==='[data-catalog-row]'?[f.row,other.row]:[];await f.mount();await submit(f.form);assert.match(other.inputs.field.validationMessage,/unique/);f.inputs.field.value='site.other';f.inputs.field.oninput();assert.equal(other.inputs.field.validationMessage,'');await submit(f.form);assert.equal(writes,1);});

test('correcting the marked catalog mapping also clears its own visible error',async()=>{const f=catalogFixture(async()=>({revision:1,fields:[field({field:'invalid'})]}));await f.mount();await submit(f.form);assert.match(f.error.textContent,/unique/);f.inputs.field.value='site.valid';f.inputs.field.oninput();assert.equal(f.inputs.field.validationMessage,'');assert.equal(f.error.textContent,'');});

test('catalog explicit comparison correction updates count and removes validation error without redraw',async()=>{const f=catalogFixture(async()=>({revision:1,fields:[field()]}));await f.mount();f.inputs.type.value='boolean';f.inputs.type.oninput();await submit(f.form);const html=f.host.innerHTML;f.op.checked=true;f.op.onchange();assert.equal(f.details.textContent,'Allowed comparisons (1)');assert.doesNotMatch(f.error.textContent,/Select at least one/);assert.match(f.error.textContent,/Removed incompatible comparisons/);assert.equal(f.host.innerHTML,html);});
test('correcting a catalog display name clears its row error without losing the typed value',async()=>{const f=catalogFixture(async()=>({revision:1,fields:[field({label:' '})]}));await f.mount();await submit(f.form);assert.match(f.error.textContent,/readable name/);f.inputs.label.value='Exact new name';f.inputs.label.oninput();assert.equal(f.error.textContent,'');assert.equal(f.inputs.label.value,'Exact new name');});
