import {InterpretationEditor} from '/workbench/frontend/components/interpretations.js';
import {Collaboration,pointerParts} from '/workbench/frontend/components/collaboration.js';
import {SourceWorkspace} from '/workbench/frontend/components/source-workspace.js';
import {SubmissionDrawer} from '/workbench/frontend/components/submission-drawer.js';
const q=s=>document.querySelector(s),info=await fetch('/fixture-info').then(r=>r.json()),log=[],clone=structuredClone;
const record=value=>{log.push(value);q('#log').textContent=JSON.stringify(log,null,2);};
const flag=id=>{const input=q('#'+id),value=input.checked;input.checked=false;return value;};
const delay=async()=>{if(flag('delay'))await new Promise(r=>setTimeout(r,1800));};
const message=text=>q('#message').textContent=text;
const dialog=(html,bind)=>{const el=q('#mw-dialog'),trigger=document.activeElement;if(el.open)el.close();el.innerHTML='<button id="fixture-close" type="button">Close fixture dialog</button>'+html;el.querySelector('#fixture-close').onclick=()=>el.close();bind?.(el);el.showModal();el.onclose=()=>trigger?.isConnected&&trigger.focus();};
const live=async(path,body)=>{record({transport:'isolated HTTP',path,body});const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':info.csrf},body:JSON.stringify(body)}:{}),result=await response.json();if(!response.ok)throw Object.assign(Error(result.error||'Fixture request failed'),{status:response.status,definitive:response.status<500});return result;};
let ai=false;const runs=new Map();
const requirements={selected:info.units[0],doc:info.sessions[0],dirty:false,orderedSessions:()=>info.sessions,rootIds:doc=>Object.keys(doc.units),label:id=>'R'+(info.units.indexOf(id)+1)};
const m={id:info.material.id,state:{actor:{id:'fixture'}},material:info.material,draft:clone(info.material),collaboration:{readonly:false},requirements,q,dialog,updateNavigationLock(){},message,unsavedDialog(){message('Unsaved work remains.');},revealPane(){},api:async(path,body)=>{
 if(path==='/api/interpretations/generate'){record({transport:'synthetic generation',path,body});await delay();let run=runs.get(body.request_id);if(run&&run.digest!==JSON.stringify(body))throw Object.assign(Error('Request changed'),{definitive:true});if(!run){run={id:body.request_id,unit_id:body.unit_id,status:'running',context_fingerprint:body.context_fingerprint,suggestions:clone(editor.draft.fields),check_design:clone(editor.draft.check_design),digest:JSON.stringify(body)};runs.set(body.request_id,run);}if(flag('lose-generation'))throw Error('Synthetic lost start response');return clone(run);}
 if(path.startsWith('/api/interpretations/run?')){record({transport:'synthetic status',path});await delay();if(flag('fail-status'))throw Error('Synthetic status unavailable');const id=new URL(path,location.origin).searchParams.get('id');return {...clone(runs.get(id)),status:'ready'};}
 const result=await live(path,body);if(ai&&path.startsWith('/api/interpretations?'))result.provider={available:true,destination:'Local synthetic fixture; no network model',model:'fixture-only'};return result;
}};
const editor=new InterpretationEditor(m);m.interpretations=editor;requirements.selectFromInterpretation=async id=>{requirements.selected=id;await editor.open(id);};
q('#source').textContent=info.material.blocks.map(b=>b.text).join('\n\n');q('#reopen').onclick=()=>editor.action('reload',q('#reopen')).catch(e=>message(e.message));q('#enable-ai').onclick=()=>{ai=true;editor.draft.provider={available:true,destination:'Local synthetic fixture; no model API',model:'fixture-only'};editor.render();message('Synthetic AI enabled. Do not save an approval for this simulated run.');};
q('#competing-save').onclick=async()=>{try{const doc=await live('/api/interpretations?'+new URLSearchParams({unit_id:info.units[0]}));doc.fields.verification.value+=' Other tab correction.';const result=await live('/api/interpretations/save',{request_id:crypto.randomUUID(),unit_id:doc.unit_id,expected_revision:doc.revision,context_fingerprint:doc.context.fingerprint,linked_material_ids:doc.linked_material_ids,fields:doc.fields,check_design:doc.check_design,approve_cards:{},action:'save'});message('Another synthetic tab saved revision '+result.revision+'. Your page draft is unchanged.');}catch(e){message(e.message);}};
q('#evidence').onclick=async()=>record(await fetch('/fixture-evidence').then(r=>r.json()));
const differences=[{id:'title',path:'/title',resolution:'edit',current:'Current title',incoming:'Submitted title',base:'Base title'},{id:'score',path:'/blocks/b/score',conflict:true,current:12,incoming:14,base:10},{id:'wording',path:'/blocks/a/text',resolution:'auto_incoming',current:'Current passage',incoming:'Submitted passage',base:'Base passage'},{id:'source-note',path:'/source_review/note',resolution:'current',current:'Current note',incoming:'Submitted note',base:'Base note'},{id:'same',path:'/metadata/topic',resolution:'same',current:'Anchoring',incoming:'Anchoring',base:'Anchoring'}];
let merge={merge_id:'fixture-merge',material:{id:'fixture-material',title:'Human edited title',revision:1,blocks:[{id:'b',type:'text',text:'Numeric block',score:12},{id:'a',type:'text',text:'Submitted passage'}],metadata:{topic:'Anchoring'}},source_review:{note:'Current note'},differences:clone(differences),unresolved:['score']};
const setValue=(preview,diff,value)=>{let parts=pointerParts(diff.path),target=parts[0]==='source_review'?preview:preview.material;if(parts[0]==='blocks'&&parts.length>1){target=target.blocks.find(b=>b.id===parts[1]);parts=parts.slice(2);}for(const part of parts.slice(0,-1))target=target[part];target[parts.at(-1)]=clone(value);};
const resolvePreview=async(preview,body)=>{record({transport:'synthetic merge',body});await delay();if(flag('merge-fail'))throw Object.assign(Error('Synthetic preview rejected; keep your typed correction.'),{definitive:true});const result=clone(preview);for(const [id,decision]of Object.entries(body.decisions)){const diff=result.differences.find(d=>d.id===id);setValue(result,diff,decision.action==='edit'?decision.value:diff[decision.action]);diff.resolution=decision.action;result.unresolved=result.unresolved.filter(x=>x!==id);}return result;};
const w={state:{actor:{id:'fixture'}},token:{},id:merge.material.id,root:q('#merge'),q,dialog,message,busy:false,opening:false,updateBar(){},clearReader(){},loadReader:async()=>{},fromMaterial:material=>({blocks:material.blocks,issues:[],checked_scope:[]}),renderMaterial(){q('#mw-content').innerHTML=collaboration.mergeSummary()+collaboration.globalDifferences()+this.draft.blocks.map(b=>collaboration.blockMarkup(b)).join('');},api:async(path,body)=>{if(path.endsWith('/resolve'))return merge=await resolvePreview(merge,body);throw Error('Fixture blocks '+path);},jumpToBlock(index){q('#mw-content').querySelectorAll('[data-difference]')[index]?.scrollIntoView();},canLeave:()=>true};
const collaboration=new Collaboration(w);collaboration.state={mode:'coordinator'};w.collaboration=collaboration;q('#merge').onclick=e=>{const b=e.target.closest('[data-action]');if(b)collaboration.action(b.dataset.action,b).catch(error=>message(error.message));};
let sourceMerge={merge_id:'fixture-source',source_id:'FX007',actor:'Fixture author',source_review:{fields:{title:'Human edited source'},note:'Current source note'},differences:[{id:'source-title',path:'/source_review/fields/title',resolution:'edit',current:'Current source',incoming:'Submitted source',base:'Base source'}],unresolved:[]};
const sources=Object.create(SourceWorkspace.prototype);Object.assign(sources,{token:{},q,dialog,message,showDetail(){},merge:sourceMerge,api:async(path,body)=>{if(path.endsWith('/resolve'))return sourceMerge=await resolvePreview(sourceMerge,body);throw Error('Fixture blocks '+path);}});
let digest=1;const receipts=new Map(),frozen=new Map(),items=[{type:'source',key:'synthetic-source',title:'Synthetic source review'},{type:'task',key:'synthetic-task',title:'Synthetic task result'}];
const drawerHost={state:{actor:{id:'fixture'}},dialog,message,api:async(path,body)=>{record({transport:'synthetic collection',path,body});await delay();if(path.includes('collection-catalogue'))return {items};if(path.endsWith('collection-preview'))return {item:{actor:'Fixture contributor'},current_digest:'digest-'+digest,current:{note:'Current task revision '+digest},proposed:{note:'Submitted evidence stays unchanged'},base:{note:'Starting evidence'},conflict:false};if(path.endsWith('collection-adopt')){if(flag('task-expire')){digest++;throw Object.assign(Error('Task changed after comparison. Reopen it.'),{definitive:true,status:400});}if(!receipts.has(body.request_id))receipts.set(body.request_id,{status:'adopted',choice:body.choice});if(flag('task-unknown'))throw Error('Synthetic lost adoption response');if(flag('task-pending'))return {status:'pending',result:{message:'Awaiting owner receipt'}};return receipts.get(body.request_id);}throw Error('Fixture blocks '+path);}};
drawerHost.api.download=async(path,body)=>{record({transport:'synthetic freeze',path,body});await delay();let saved=frozen.get(body.request_id);if(!saved){saved={downloadUrl:URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'text/plain'})),filename:'synthetic-frozen-selection.txt'};frozen.set(body.request_id,saved);}if(flag('freeze-unknown'))throw Error('Synthetic lost freeze response');const a=document.createElement('a');a.href=saved.downloadUrl;a.download=saved.filename;a.click();return saved;};
q('#task-open').onclick=()=>new SubmissionDrawer(drawerHost).compare('synthetic-task').catch(e=>message(e.message));q('#freeze-open').onclick=()=>new SubmissionDrawer(drawerHost).open().catch(e=>message(e.message));
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.fixture-panel').forEach(p=>p.hidden=p.id!==b.dataset.panel);});
await editor.open(info.units[0]);await collaboration.showPreview(merge);sources.renderMerge();window.fixture={editor,m,info,collaboration,sources,drawerHost};
