import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {materialSystems,systemCards,renderDashboard} from '../ui/dashboard.js';
const code = await readFile(new URL('../ui/materials.js', import.meta.url), 'utf8');
const {Materials,materialStatus} = await import('../ui/materials.js');
const storage = new Map();
globalThis.localStorage = {getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)};
const material = () => ({id:'one',title:'Isolated material',source:{source_id:'fixture',snapshot_id:'snapshot-1'},revision:4,content_revision:2,blocks:[{id:'text-1',type:'text',text:'Human correction',source_refs:[{scope_id:'page:1',page:1}]}],scope:[{id:'page:1',label:'Page 1'}],issues:[],checked_scope:[],association_review_required:true,content_status:'draft',candidates:[]});
function instance(){
  const x=new Materials();x.state={actor:{id:'reviewer-1',name:'Isolated reviewer'}};x.material=material();x.id=x.material.id;x.localBase=4;x.draft=x.fromMaterial(x.material);x.dirty=true;x.token={};x.items=[x.material];x.nodes=new Map();x.q=s=>{if(!x.nodes.has(s))x.nodes.set(s,{innerHTML:'',textContent:'',scrollTop:0});return x.nodes.get(s);};x.root={querySelectorAll:()=>[]};x.renderMaterial=()=>{};x.renderContent=()=>{};x.message=(text,kind)=>x.lastMessage={text,kind};return x;
}
test('save sends one material snapshot and never confirms or extracts', async()=>{
  const x=instance(),calls=[];x.api=async(path,body)=>{calls.push({path,body});return {status:'applied',material:{...material(),revision:5}};};
  await x.save();assert.equal(calls.length,1);assert.equal(calls[0].path,'/api/material/save');assert.equal(calls[0].body.material_id,'one');assert.equal(calls[0].body.expected_revision,4);assert.equal(calls[0].body.blocks[0].text,'Human correction');assert.equal('actor' in calls[0].body,false);assert.equal(x.dirty,false);assert.equal(x.material.content_status,'draft');
});
test('in-flight save prevents navigation and makes editor inert',async()=>{
  const x=instance();let complete;x.api=()=>new Promise(resolve=>complete=resolve);const request=x.save();assert.equal(x.busy,true);assert.equal(x.canLeave(),false);assert.equal(x.q('#mw-content').inert,true);complete({status:'applied',material:{...material(),revision:5}});await request;assert.equal(x.q('#mw-content').inert,false);assert.equal(x.canLeave(),true);
});
test('a conflicting save preserves local changes and original revision guard',async()=>{
  const x=instance(),original=x.draft;x.api=async()=>({status:'conflict',conflict_id:'durable-1',material:{...material(),revision:6}});assert.equal(await x.save(),false);assert.equal(x.draft,original);assert.equal(x.localBase,4);assert.equal(x.dirty,true);assert.equal(x.localConflict,true);assert.match(x.lastMessage.text,/retained/);
});
test('retry after uncertain save reuses request identity',async()=>{
  const x=instance(),calls=[];let first=true;x.api=async(path,body)=>{calls.push(body);if(first){first=false;throw Error('Connection interrupted');}return {status:'applied',material:{...material(),revision:5}};};
  await x.save();assert.equal(x.dirty,true);await x.save();assert.equal(calls[0].request_id,calls[1].request_id);assert.equal(calls[0].expected_revision,calls[1].expected_revision);
});
test('local draft includes merge intent and is scoped by reviewer and material',()=>{
  storage.clear();const x=instance();x.pendingMerge='candidate-2';x.persistDraft();const first=JSON.parse(storage.get('material-draft-v1:reviewer-1:one'));assert.equal(first.pendingMerge,'candidate-2');assert.equal(first.expected_revision,4);x.id='two';x.draft.blocks[0].text='Second material';x.persistDraft();assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one')).draft.blocks[0].text,'Human correction');assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:two')).draft.blocks[0].text,'Second material');
});
test('changed content preserves provisional checks for server impact calculation',()=>{
  const x=instance();x.draft.checked_scope=['page:1'];x.draft.association_reviewed=true;x.changed(true);assert.deepEqual(x.draft.checked_scope,['page:1']);assert.equal(x.bodyChanged,true);assert.equal(x.draft.association_reviewed,false);assert.equal(x.dirty,true);
});
test('saved checklist survives readback only when association review is resolved',()=>{
  const x=instance();assert.equal(x.fromMaterial({...material(),association_review_required:false}).association_reviewed,false);assert.equal(x.fromMaterial({...material(),association_review_required:false,checked_scope:['page:1']}).association_reviewed,true);assert.equal(x.fromMaterial({...material(),association_review_required:true,checked_scope:['page:1']}).association_reviewed,false);
});
test('stale candidate permits explicit keep or merge but disables direct adoption',async()=>{
  const x=instance();x.material.candidates=[{id:'candidate-1',status:'ready',stale:true,complete:true,input_revision:1,blocks:[]}];x.api=async()=>x.material.candidates[0];x.dialog=html=>x.dialogHTML=html;await x.candidateDialog('candidate-1');assert.match(x.dialogHTML,/<button id="mw-adopt" disabled>/);assert.match(x.dialogHTML,/<button id="mw-keep">/);assert.match(x.dialogHTML,/<button id="mw-edit-merge">/);assert.match(x.dialogHTML,/older input/);
});
test('large material exposes explicit block pages instead of hidden content loss',()=>{
  const x=instance();x.draft.blocks=Array.from({length:95},(_,i)=>({id:String(i),type:'text',text:String(i)}));x.blockPage=1;assert.match(x.blockNavigation(),/Blocks 41–80 of 95/);assert.match(x.blockNavigation(),/Previous blocks/);assert.match(x.blockNavigation(),/Next blocks/);
});
test('an untouched recovered tab does not rewrite another tab local draft',()=>{
  storage.clear();const first=instance();first.tabIdentity='tab-a';first.draftTouched=true;first.persistDraft();const recovered=instance();recovered.tabIdentity='tab-b';recovered.draftTouched=false;recovered.draft.blocks[0].text='Old recovered content';first.draft.blocks[0].text='New work in original tab';first.persistDraft();recovered.persistDraft();assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one')).draft.blocks[0].text,'New work in original tab');assert.equal(storage.has('material-draft-v1:reviewer-1:one:tab-b'),false);
});
test('two editing tabs retain independent draft journals',()=>{
  storage.clear();const a=instance(),b=instance();a.tabIdentity='a';b.tabIdentity='b';a.draft.blocks[0].text='Draft A';b.draft.blocks[0].text='Draft B';a.persistDraft();b.persistDraft();assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one:a')).draft.blocks[0].text,'Draft A');assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one:b')).draft.blocks[0].text,'Draft B');
});

test('overview counts material snapshots and current human reviews independently from blocks',()=>{
  const sourceCard={key:'system1',retained:'source authority'};
  const rows=[{content_status:'draft',blocks:Array(800).fill({})},{content_status:'content_review_complete'},{content_status:'content_review_complete',source_stale:true},{content_status:'content_review_complete',candidates:[{status:'ready'}]},{content_status:'content_review_complete',source_issues:[{reason:'Missing source page'}]}];
  const systems=materialSystems({systems:[sourceCard,{key:'system2',pending:{value:9999}}],material_workbench:{status:'ready',data:{materials:rows,sources:Array(8).fill({})}}});
  assert.deepEqual(systems[0],{...sourceCard,label:'Source governance',title:'Source Management System'});assert.deepEqual(sourceCard,{key:'system1',retained:'source authority'});assert.equal(systems[1].pending.value,3);assert.deepEqual(systems[1].metrics.map(m=>m.value),[5,1,8,1]);assert.deepEqual(systems.map(s=>s.key),['system1','system2']);assert.match(systems[1].note,/Requirement structuring remains unconnected/);assert.equal(systems[1].action.view,'system2');
});
test('overview fetch failure stays unavailable and displays the escaped underlying error',()=>{
  const systems=materialSystems({material_workbench:{status:'error',error:'Reader <unavailable> due to source lock'}}),card=systems[0];assert.equal(card.pending.value,null);assert.ok(card.metrics.every(m=>m.value===null));const html=systemCards(systems);assert.match(html,/Read failed/);assert.match(html,/Reader &lt;unavailable&gt; due to source lock/);assert.match(html,/Unavailable/);assert.doesNotMatch(html,/>0</);
});
test('overview loading does not present fabricated zero material counts',()=>{
  const card=materialSystems({})[0];assert.equal(card.pending.value,null);assert.equal(card.pending.display,'Loading…');assert.ok(card.metrics.every(m=>m.value===null));
});
test('overview renders new entry and retains explicit legacy navigation',()=>{
  const allButton={};const container={innerHTML:'',querySelector:s=>s==='#dashboard-all'?allButton:null,querySelectorAll:()=>[]};
  renderDashboard(container,{as_of:0,counts:{sources:0,pending:0,stored:0,included:0,missing:0},selection:[],issues:[],categories:[],priority:[],systems:[],material_workbench:{status:'ready',data:{materials:[],sources:[]}}},()=>{},()=>{});
  assert.match(container.innerHTML,/Sources → Material workbench/);assert.doesNotMatch(container.innerHTML,/data-open-system="system3"|Three-system/);assert.match(container.innerHTML,/third pane inside each material/);assert.match(container.innerHTML,/data-legacy-view="legacyHistory"/);assert.match(container.innerHTML,/Retained weekly inspection records/);assert.doesNotMatch(container.innerHTML,/complete requirement workflow|Open review demo|Requirements extracted/);
});
test('switching material clears source-specific action notices',async()=>{
  storage.clear();const x=instance();x.dirty=false;x.lastMessage={text:'Original problem sent; confirmation unavailable.'};x.api=async()=>({...material(),id:'two',source:{source_id:'other-source',snapshot_id:'snapshot-2'}});x.loadReader=async()=>{};await x.open('two');assert.equal(x.id,'two');assert.equal(x.lastMessage.text,'');
});
test('PDF reader presents a bound page image without requiring a native PDF plugin',()=>{
  const x=instance(),html=x.pdfMarkup({page:2,pages:6,image:'data:image/png;base64,fixture',native_text:'Original <text>',page_warning:'Native text is unverified.'});assert.match(html,/Saved original PDF page 2 of 6/);assert.match(html,/src="data:image\/png;base64,fixture"/);assert.match(html,/separate from the page image/);assert.match(html,/Original &lt;text&gt;/);assert.doesNotMatch(html,/<iframe/);assert.match(html,/Optional browser PDF viewer/);
});
test('scan-only PDF reader does not claim selectable original text or OCR completion',()=>{
  const x=instance(),html=x.pdfMarkup({page:1,pages:1,image:'data:image/png;base64,scan',native_text:''});assert.match(html,/No native text on this page/);assert.match(html,/manually transcribe/);assert.match(html,/No OCR has run/);assert.doesNotMatch(html,/<pre/);
});
test('PDF previous and next navigation stay within complete original page bounds',async()=>{
  const x=instance(),pages=[];x.reader={kind:'pdf',page:1,pages:3};x.loadReader=async p=>pages.push(p.page);await x.readerAction('reader-pdf-prev');await x.readerAction('reader-pdf-next');x.reader.page=3;await x.readerAction('reader-pdf-next');await x.readerAction('reader-pdf-prev');assert.deepEqual(pages,[1,2,3,2]);
});
test('PDF zoom changes only page image width and preserves fit-width option',()=>{
  const x=instance();x.q('.mw-pdf-page-image').style={};x.pdfZoom='150';x.setPdfZoom({width:612});assert.equal(x.q('.mw-pdf-page-image').style.width,'1224px');x.pdfZoom='page-width';x.setPdfZoom({width:612});assert.equal(x.q('.mw-pdf-page-image').style.width,'100%');
});
test('HTTP 409 thrown by the real API helper opens conflict recovery without discarding draft',async()=>{
  storage.clear();const x=instance(),draft=x.draft,newer={...material(),revision:5};x.renderContent=()=>x.conflictControlsRendered=x.localConflict;
  x.api=async()=>{const error=Error('newer_material_revision_saved_draft_preserved');error.current=newer;error.status=409;error.definitive=true;error.conflict_id='durable-http-conflict';error.details={status:'conflict',material:newer,conflict_id:'durable-http-conflict'};throw error;};
  assert.equal(await x.save(),false);assert.equal(x.draft,draft);assert.equal(x.localBase,4);assert.equal(x.localConflict,true);assert.equal(x.conflictControlsRendered,true);assert.equal(x.conflictResult.conflict_id,'durable-http-conflict');assert.match(x.lastMessage.text,/Compare saved and local/);assert.doesNotMatch(x.lastMessage.text,/newer_material_revision/);assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one')).conflict_id,'durable-http-conflict');
});
test('legacy Error.current shape is also recoverable as a guarded conflict',async()=>{
  const x=instance();x.api=async()=>{const error=Error('newer_material_revision_saved_draft_preserved');error.current={...material(),revision:6};error.definitive=true;throw error;};await x.save();assert.equal(x.localConflict,true);assert.equal(x.draft.blocks[0].text,'Human correction');assert.equal(x.localBase,4);
});
test('conflict merge preserves newer unique blocks, local edits and unresolved issues',()=>{
  const x=instance();x.draft.issues=[{id:'issue',message:'Previously checked',resolved:true}];const newer={...material(),revision:5,blocks:[{id:'new-heading',type:'heading',text:'New heading',level:1},{id:'text-1',type:'text',text:'Other reviewer edit'},{id:'new-tail',type:'text',text:'New unseen paragraph'}],issues:[{id:'issue',message:'Reopened issue',resolved:false},{id:'new-issue',message:'New source issue',resolved:false}]};
  const merged=x.conflictDraft(newer);assert.deepEqual(merged.blocks.map(b=>b.id),['new-heading','text-1','new-tail']);assert.equal(merged.blocks[1].text,'Human correction');assert.equal(merged.issues.find(i=>i.id==='issue').resolved,false);assert.match(merged.issues.find(i=>i.id==='issue').message,/Reopened issue/);assert.match(merged.issues.find(i=>i.id==='issue').message,/Previously checked/);assert.equal(merged.issues.length,2);assert.deepEqual(merged.checked_scope,[]);assert.equal(merged.association_reviewed,false);assert.equal(x.draft.blocks.length,1);
  assert.equal(x.conflictDraft(newer,{'text-1':'saved'}).blocks[1].text,'Other reviewer edit');
});

test('ready extraction candidate has a processing label without pretending content is adopted',()=>{
  const status=materialStatus({content_status:'not_extracted',candidates:[{status:'ready',blocks:Array(120).fill({})}]});assert.equal(status.content,'No adopted content');assert.match(status.processing,/Candidate ready · 120 blocks · adoption pending/);assert.equal(status.group,'In progress');assert.equal(status.currentReviewed,false);
});
test('processing status distinguishes running, partial and failure without changing content review',()=>{
  const base={content_status:'draft'};assert.match(materialStatus({...base,candidates:[{status:'running'}]}).processing,/Extraction running/);assert.match(materialStatus({...base,candidates:[{status:'partial',blocks:[{}]}]}).processing,/Partial candidate/);assert.match(materialStatus({...base,candidates:[{status:'failed'}]}).processing,/Extraction failed/);assert.equal(materialStatus({...base,candidates:[{status:'failed'}]}).content,'Content draft');
});
test('old confirmations with source or candidate issues are not current reviewed materials',()=>{
  const complete={content_status:'content_review_complete'};assert.equal(materialStatus(complete).group,'Content reviewed');for(const flags of [{source_issues:[{reason:'Missing image'}]},{source_check_error:'Unavailable'},{candidates:[{status:'ready'}]}]){const state=materialStatus({...complete,...flags});assert.equal(state.currentReviewed,false);assert.equal(state.group,'Needs follow-up');assert.equal(state.content,'Previous content confirmation retained');}
  const old=materialStatus({...complete,source_stale:true});assert.equal(old.group,'Historical versions');assert.equal(old.content,'Historical content confirmation');assert.equal(old.currentReviewed,false);
});
test('list and right pane qualify preserved confirmations consistently',()=>{
  const x=instance();x.items=[{...material(),id:'ok',title:'Current reviewed',content_status:'content_review_complete'},{...material(),id:'old',title:'Old snapshot',content_status:'content_review_complete',source_stale:true},{...material(),id:'waiting',title:'Waiting candidate',content_status:'content_review_complete',candidates:[{status:'ready',blocks:[{}]}]}];x.renderList();const html=x.q('#mw-material-list').innerHTML;assert.match(html,/Pending materials · 3/);assert.match(html,/Historical content confirmation/);assert.match(html,/Previous content confirmation retained/);
  x.material=x.items[2];x.dirty=false;x.updateBar();assert.match(x.q('#mw-requirement-state').innerHTML,/Previous content confirmation retained/);assert.match(x.q('#mw-requirement-state').innerHTML,/Candidate reconciliation pending/);assert.doesNotMatch(x.q('#mw-requirement-state').innerHTML,/class="mw-state"/);assert.equal(x.q('[data-action="review"]').disabled,true);
});

test('old client upgrade response preserves local draft and gives recovery direction',async()=>{const x=instance(),before=x.draft;x.api=async()=>{const e=Error('material_api_version_required');e.status=426;e.definitive=true;throw e;};assert.equal(await x.save(),false);assert.equal(x.draft,before);assert.equal(x.dirty,true);assert.match(x.lastMessage.text,/Reload this browser page to recover/);});
test('pending source open cannot extract or save the previously active material',async()=>{const x=instance();x.dirty=false;x.q('#mw-source').value='other';x.loadReader=async()=>{};const calls=[];let finishOpen;x.api=async(path,body)=>{calls.push({path,body});if(path==='/api/material/open')return new Promise(resolve=>finishOpen=resolve);return {...material(),id:'two'};};const request=x.action('open-source',{dataset:{},closest:()=>null});assert.equal(x.opening,true);assert.equal(x.q('[data-action="extract"]').disabled,true);assert.equal(x.q('#mw-source').disabled,true);assert.equal(x.q('[data-action="open-source"]').disabled,true);assert.equal(x.canLeave(),false);assert.equal(await x.mutate('/api/material/extract',{},'should not run'),false);finishOpen({...material(),id:'two'});await request;assert.equal(x.id,'two');assert.equal(x.opening,false);assert.equal(calls.some(c=>c.path==='/api/material/extract'),false);});
test('pending saved material read locks old actions and errors restore previous context',async()=>{const x=instance();x.dirty=false;let reject;x.api=()=>new Promise((_,fail)=>reject=fail);const request=x.open('two');assert.equal(x.opening,true);assert.equal(x.q('#mw-content').inert,true);assert.equal(x.q('[data-action="save"]').disabled,true);assert.equal(await x.mutate('/api/material/extract',{},''),false);reject(Error('Unavailable fixture read'));await request;assert.equal(x.id,'one');assert.equal(x.opening,false);assert.equal(x.q('#mw-content').inert,false);assert.match(x.lastMessage.text,/Unavailable fixture read/);});
test('large draft waits for durable browser write and keeps per-tab identity without duplicate shared body',async()=>{const x=instance();x.tabIdentity='large-tab';x.draft.blocks[0].text='x'.repeat(1100000);let finish,entries;x.writeLargeDraft=value=>{entries=value;return new Promise(resolve=>finish=resolve);};x.persistDraft();assert.equal(x.journalState,'pending');await Promise.resolve();await Promise.resolve();assert.ok(entries['material-draft-v1:reviewer-1:one:large-tab'].draft);assert.equal(entries['material-draft-v1:reviewer-1:one'].pointer,'material-draft-v1:reviewer-1:one:large-tab');assert.equal(entries['material-draft-v1:reviewer-1:one'].draft,undefined);finish();await x.journalPromise;assert.equal(x.journalState,'saved');});
test('browser large-draft storage failure is visible and does not prevent server save',async()=>{const x=instance();x.draft.blocks[0].text='x'.repeat(1100000);x.writeLargeDraft=async()=>{throw Error('isolated quota failure');};x.persistDraft();await x.journalPromise;assert.equal(x.journalState,'failed');assert.equal(x.dirty,true);assert.match(x.lastMessage.text,/Keep this page open/);x.api=async()=>({material:{...material(),revision:5}});assert.equal(await x.save(),true);assert.equal(x.dirty,false);assert.equal(x.material.revision,5);});

test('switching materials clears prior original before draft recovery completes',async()=>{const x=instance();x.dirty=false;x.q('#mw-original-toolbar').innerHTML='Old sheet controls';x.q('#mw-reader').innerHTML='Old source table';x.reader={kind:'xlsx',sheet:'Previous'};let recover;x.recoverDraft=()=>new Promise(resolve=>recover=resolve);x.api=async()=>({...material(),id:'two'});x.loadReader=async()=>{};const request=x.open('two');await Promise.resolve();await Promise.resolve();await Promise.resolve();assert.equal(x.id,'two');assert.equal(x.reader,null);assert.equal(x.q('#mw-original-toolbar').innerHTML,'');assert.doesNotMatch(x.q('#mw-reader').innerHTML,/Old source/);assert.match(x.q('#mw-reader').innerHTML,/Opening saved original/);recover(null);await request;});
test('reloading original removes stale controls and ignores old in-flight response',async()=>{const x=instance();x.q('#mw-original-toolbar').innerHTML='Old page controls';x.q('#mw-reader').innerHTML='Old original';const responses=[];x.api=()=>new Promise(resolve=>responses.push(resolve));const rendered=[];x.renderReader=r=>rendered.push(r.page);const first=x.loadReader({page:1});const second=x.loadReader({page:2});assert.equal(x.reader,null);assert.equal(x.q('#mw-original-toolbar').innerHTML,'');assert.doesNotMatch(x.q('#mw-reader').innerHTML,/Old original/);responses[0]({kind:'pdf',page:1});await first;assert.deepEqual(rendered,[]);responses[1]({kind:'pdf',page:2});await second;assert.deepEqual(rendered,[2]);});

test('fallback document owner recovers prior own work before another tab shared journal',async()=>{storage.clear();const a=instance(),b=instance();a.tabIdentity='old-a';b.tabIdentity='tab-b';a.draft.blocks[0].text='Own prior document';a.persistDraft();b.draft.blocks[0].text='Other tab';b.persistDraft();const reloaded=instance();reloaded.tabIdentity='new-a';reloaded.recoveryOwner='old-a';const recovered=await reloaded.recoverDraft('one');assert.equal(recovered.draft.blocks[0].text,'Own prior document');reloaded.draft=recovered.draft;reloaded.draft.blocks[0].text='Recovered edit';reloaded.persistDraft();await reloaded.clearDraftJournal('one');assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one:tab-b')).draft.blocks[0].text,'Other tab');assert.equal(JSON.parse(storage.get('material-draft-v1:reviewer-1:one:old-a')).draft.blocks[0].text,'Own prior document');assert.equal(await reloaded.recoverDraft('one'),undefined);});

test('fallback repeated reloads keep per-material last-written owners despite newer shared drafts',async()=>{storage.clear();const savedSession=globalThis.sessionStorage;const session=new Map();globalThis.sessionStorage={getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)};try{const first=instance();first.tabIdentity='first-owner';first.draft.blocks[0].text='Own material one';first.persistDraft();first.id='two';first.draft.blocks[0].text='Own material two';first.persistDraft();const second=instance();second.tabIdentity='new-document-1';second.recoveryOwner='legacy-owner';assert.equal((await second.recoverDraft('one')).draft.blocks[0].text,'Own material one');second.draftTouched=false;second.persistDraft();const otherSession=new Map();globalThis.sessionStorage={getItem:k=>otherSession.get(k)||null,setItem:(k,v)=>otherSession.set(k,v),removeItem:k=>otherSession.delete(k)};const other=instance();other.tabIdentity='other-tab';other.draft.blocks[0].text='Newer other tab';other.persistDraft();globalThis.sessionStorage={getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)};const third=instance();third.tabIdentity='new-document-2';third.recoveryOwner='empty-owner';assert.equal((await third.recoverDraft('one')).draft.blocks[0].text,'Own material one');assert.equal((await third.recoverDraft('two')).draft.blocks[0].text,'Own material two');assert.equal(session.get('material-draft-owner-v1:reviewer-1:one'),'first-owner');assert.equal(session.get('material-draft-owner-v1:reviewer-1:two'),'first-owner');third.state.actor.id='other-reviewer';assert.equal(await third.recoverDraft('one'),undefined);}finally{globalThis.sessionStorage=savedSession;}});
test('large journal records its recovery owner only after durable write succeeds',async()=>{const savedSession=globalThis.sessionStorage,session=new Map();globalThis.sessionStorage={getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)};try{const x=instance();x.tabIdentity='large-owner';x.draft.blocks[0].text='x'.repeat(1100000);let finish;x.writeLargeDraft=()=>new Promise(resolve=>finish=resolve);x.persistDraft();await Promise.resolve();await Promise.resolve();assert.equal(session.size,0);finish();await x.journalPromise;assert.equal(session.get('material-draft-owner-v1:reviewer-1:one'),'large-owner');}finally{globalThis.sessionStorage=savedSession;}});
