import {installGlobalSettings} from '/workbench/frontend/components/global-settings.js';
import {settings} from '/workbench/frontend/components/extraction.js';
const $=s=>document.querySelector(s),clone=structuredClone,log=[];
function record(path,body){const safe=body?clone(body):null;if(safe&&'api_key'in safe)safe.api_key=safe.api_key?'[provided, omitted]':'[empty]';log.push({path,body:safe});$('#fixture-log').textContent=log.map(x=>JSON.stringify(x)).join('\n');}
const ai={revision:1,endpoint:'https://synthetic.invalid/v1/chat/completions',model:'synthetic-model',max_bytes:10000,enabled:false,has_key:true,status:'Disabled'},catalog={revision:1,fields:[{field:'site.temperature',label:'Temperature',description:'Synthetic, no site data connected',type:'string',operators:['contains']},{field:'site.count',label:'Count',description:'Synthetic count',type:'integer',operators:['equal']}]},policy={revision:1,system1:.9,content:.9,requirement:.9,system3:.82};
let schedule={enabled:false,interval_days:7,sample_size:5,assignee:'Absent reviewer',timezone:'Europe/Oslo'},scheduleRevision=1,importCount=0;
function report(){const type=$('#dispatch').value;if(type==='absent')return null;if(['scheduled','disabled'].includes(type))return {status:type};return {status:'complete',at:'2026-09-20T10:00:00Z',completed_at:'2026-09-20T10:00:02Z',assignee:'Earlier reviewer',requested_count:5,eligible_count:type==='zero'?0:3,selected_count:type==='zero'?0:3,items:type==='zero'?[]:[{material_id:'FX001',status:'created'},{material_id:'FX002',status:'already_pending'},{material_id:'FX003',status:'skipped',reason:'Synthetic archive revision changed'}]};}
const readSchedule=()=>({revision:scheduleRevision,settings:clone(schedule),last_run:'2026-09-20T10:00:02Z',next_run:null,can_schedule:!$('#readonly').checked,can_edit_confidence:!$('#readonly').checked,status:report()});
const error=message=>Object.assign(Error(message),{definitive:true,status:400});
async function mode(target,label){const value=$('#save-mode').value;$('#save-mode').value='success';if(value==='delay')await new Promise(resolve=>setTimeout(resolve,5000));if(value==='fail')throw error('Synthetic save rejected; entered values are retained.');if(value==='conflict'){if(target===schedule){scheduleRevision++;schedule={...schedule,interval_days:21};}else{target.revision++;if(target===ai)target.model='newer-saved-model';if(target===catalog)target.fields[0].label='Newer saved name';if(target===policy){target.content=.94;target.system3=.77;}}throw error(label+' changed in another window. Reload before saving.');}}
async function api(path,body){record(path,body);if(path==='/api/settings/ai'){if(!body)return clone(ai);await mode(ai,'API settings');if(body.revision!==ai.revision)throw error('API settings changed. Reload before saving.');Object.assign(ai,{endpoint:body.endpoint,model:body.model,enabled:body.enabled,max_bytes:body.max_bytes,has_key:body.clear_key?false:!!body.api_key||ai.has_key,revision:ai.revision+1});return clone(ai);}
 if(path==='/api/settings/site-catalog'){if(!body)return clone(catalog);await mode(catalog,'The catalog');if(body.revision!==catalog.revision)throw error('The catalog changed. Reload before saving.');Object.assign(catalog,{fields:clone(body.fields),revision:catalog.revision+1});return clone(catalog);}
 if(path==='/api/settings'){if(!body)return {policy:clone(policy),history:[]};await mode(policy,'The settings');if(body.revision!==policy.revision)throw error('The settings changed. Reload before saving.');Object.assign(policy,body.values,{revision:policy.revision+1});return {status:'applied',policy:clone(policy)};}
 if(path==='/api/automation'){if(!body)return readSchedule();await mode(schedule,'Automation settings');if(body.revision!==scheduleRevision)throw error('Automation settings changed. Reload before saving.');schedule=clone(body.settings);scheduleRevision++;return readSchedule();}
 if(path==='/api/sync/history')return {events:[],pending:[]};throw error('Unexpected fixture request: '+path);}
window.fetch=async(path,options)=>{if(path!=='/api/sync/import')throw Error('Fixture blocks all unexpected fetch calls');record(path,{filename:options.body.name,bytes:options.body.size});importCount++;const fail=$('#imports').value==='fail-success'?importCount===1:importCount===2;return {ok:!fail,json:async()=>fail?{error:'Synthetic ZIP validation failure'}:{id:'synthetic-plan',status:'preview',sender:'Fixture reviewer',items:[{key:'FX001',title:'Synthetic prior comparison',status:'unchanged',contributors:['Fixture reviewer']}],conflicts:[],validation_errors:[],applied_items:[],decisions:{}}};};
installGlobalSettings({api,getState:()=>({actors:[{name:'First reviewer'},{name:'Second reviewer'}],csrf:'fixture-only'}),canLeave:()=>true,onSynced:()=>{},notice:()=>{}});
await settings($('#standalone'),api);
