import {Materials} from '/workbench/frontend/components/materials.js';
const q=s=>document.querySelector(s),info=await fetch('/fixture-info').then(r=>r.json()),m=new Materials(),log=[],saved=structuredClone(info.material);
const record=item=>{log.push(item);q('#log').textContent=JSON.stringify(log,null,2);};
const http=async(path,body)=>{const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':info.csrf},body:JSON.stringify(body)}:{}),result=await response.json();if(!response.ok)throw Object.assign(Error(result.error||'Fixture request rejected'),{status:response.status,definitive:response.status<500});return result;};
let revision=1;
const historical=id=>({...structuredClone(saved),id,revision:0,blocks:[{id:'historical',type:'text',text:'Historical synthetic version. Restore remains a local draft.',source_refs:[{page:1}]}],checked_scope:['fixture:main'],confirmation:{actor:'Synthetic prior reviewer'}});
const sheet=()=>({kind:'spreadsheet',sheet:'Water',sheets:[{name:'Water',rows:40,columns:10}],rows:40,columns:10,row:1,column:1,row_count:40,column_count:10,source_sha256:'synthetic-r10',warnings:[],merged:[],cells:Array.from({length:40},(_,r)=>Array.from({length:10},(_,c)=>({address:String.fromCharCode(65+c)+(r+1),value:'Saved '+(r+1)+':'+(c+1),...(c===0?{formula:'=1+1',formula_present:true,cached:2,cache_status:'saved'}:{})})))});
const page=()=>({kind:'pdf',page:1,pages:1,image:'/region.svg',width:600,height:400,image_width:600,source_sha256:'synthetic-r10',warnings:[],text:'Synthetic page. The facility shall inspect the anchoring line.'});
m.api=async(path,body)=>{record({path,body});const url=new URL(path,location.origin);
 if(url.pathname==='/api/material/history'||url.pathname==='/api/material'&&url.searchParams.has('revision')){if(q('#delay').checked){q('#delay').checked=false;await new Promise(r=>setTimeout(r,5000));}if(q('#fail').checked){q('#fail').checked=false;throw Error('Synthetic history read failed');}if(url.pathname.endsWith('/history'))return {total:21,has_more:!Number(url.searchParams.get('offset')),revisions:[{revision:0,actor:'Earlier synthetic reviewer',at:'2026-09-20T10:00:00Z'}]};return {material:historical(url.searchParams.get('id'))};}
 if(url.pathname==='/api/material')return structuredClone(saved);
 if(url.pathname==='/api/material/reader')return url.searchParams.has('sheet')?sheet():page();
 if(path==='/api/material/save'){revision++;Object.assign(saved,{...structuredClone(body),id:info.material.id,revision,content_revision:revision});return {status:'applied',material:structuredClone(saved)};}
 if(url.pathname==='/api/requirements/annotations')return {material_revision:m.material.revision,spans:[],stale_sessions:[]};
 return http(path,body);
};
Object.assign(m,{root:q('#fixture-root'),state:{actor:{id:'fixture',name:'Weijie Tang'},collaboration:{peer_sync:true}},token:{},sources:[],items:[],listPage:{total:0},tabIdentity:'r10-fixture',contextKey:'r10-fixture-view',persistDraft(){},clearDraftJournal:async()=>{},renderSystemNotices(){}});
m.q=s=>m.root.querySelector(s);m.shell();m.saveKey=e=>m.saveFromKeyboard(e);window.addEventListener('keydown',m.saveKey);
async function reopen(){m.id=saved.id;m.material=structuredClone(saved);m.draft=m.fromMaterial(saved);m.dirty=false;m.bodyChanged=false;m.localBase=saved.revision;m.items=[m.material];m.notebook.reset();m.requirements.context=m.requirements.key();m.requirements.doc=null;m.requirements.sessions=[];m.requirements.selected=null;m.requirements.loading=false;m.requirements.dirty=false;m.requirements.edits=[];m.requirements.lastRender=null;m.interpretations.active=null;m.renderMaterial();await m.requirements.loadList();if(m.requirements.doc)await m.interpretations.open(Object.keys(m.requirements.doc.units)[0]);await m.loadReader();q('#fixture-status').textContent='Ready. Cmd/Ctrl+S routes to the focused pane. Real saves never imply approval.';}
q('#reset').onclick=reopen;q('#worksheet').onclick=()=>m.loadReader({sheet:'Water'});q('#page').onclick=()=>m.loadReader({page:1});q('#region').onclick=()=>m.selectImageRegion(m.draft.blocks[0]);q('#passage').onclick=()=>m.jumpToBlock(m.draft.blocks.findIndex(b=>b.id==='passage-25'));q('#saved-history').onclick=()=>m.historyDialog();q('#switch').onclick=()=>{m.id='synthetic-B';m.material={...m.material,id:m.id,title:'Synthetic B'};m.draft={...m.draft,blocks:[{id:'B',type:'text',text:'Synthetic B must not be replaced by A history.',source_refs:[{page:1}]}]};m.dirty=false;m.renderMaterial();};
q('#candidate').onclick=()=>{const d=m.interpretations.draft;if(!d)return;d.candidate={context_fingerprint:d.context.fingerprint,suggestions:{condition:{value:'Synthetic explicit B candidate',basis:'interpretation',state:'specified',references:[],gaps:[]},demand:{value:'Synthetic explicit C candidate',basis:'interpretation',state:'specified',references:[],gaps:[]}}};m.interpretations.render();};
q('#evidence').onclick=async()=>{record(await http('/fixture-evidence'));record({localMaterial:m.draft,dirty:m.dirty});};await reopen();window.fixture={m,info,log};
