import {ruleOperators} from './check-design.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const catalogOperators=kind=>Object.keys(ruleOperators).filter(k=>kind==='boolean'?['equal','not_equal','is_null','is_not_null','in','not_in'].includes(k):kind==='string'||!['contains','not_contains','begins_with','ends_with','is_empty','is_not_empty'].includes(k));
export async function catalogSettings(host,api,onSaved){
 const data=await api('/api/settings/site-catalog');let fields=structuredClone(data.fields);
 const draw=()=>{
  host.innerHTML=`<p>Configure the names and comparisons agreed with the Site Model team. This catalog starts empty and does not connect to or query their database.</p><form><div class="catalog-fields">${fields.map((f,i)=>`<fieldset data-catalog-row="${i}"><legend>${esc(f.label||'New field')}</legend><label>Display name<input data-catalog="label" required value="${esc(f.label)}"></label><label>Database mapping<input data-catalog="field" required placeholder="table.column" value="${esc(f.field)}"></label><label>Value type<select data-catalog="type">${Object.entries({string:'Text',integer:'Whole number',double:'Number',boolean:'Yes / no'}).map(([k,v])=>`<option value="${k}" ${f.type===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Meaning / agreed usage<textarea data-catalog="description">${esc(f.description)}</textarea></label><details><summary>Allowed comparisons (${f.operators.length})</summary>${catalogOperators(f.type).map(op=>`<label class="settings-check"><input type="checkbox" data-operator="${op}" ${f.operators.includes(op)?'checked':''}>${esc(ruleOperators[op])}</label>`).join('')}</details><button type="button" data-remove="${i}">Remove field</button></fieldset>`).join('')}</div><button type="button" data-add-field>Add field</button><p>Existing saved designs retain their catalog version. Changed mappings require review.</p><button type="submit" class="primary">Save field catalog</button><p data-catalog-message role="status"></p></form>`;
  host.querySelector('[data-add-field]').onclick=()=>{fields.push({field:'',label:'',type:'string',operators:['equal','not_equal'],description:''});draw();};
  host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{fields.splice(Number(b.dataset.remove),1);draw();});
  host.querySelectorAll('[data-catalog-row]').forEach(row=>{const f=fields[Number(row.dataset.catalogRow)];row.querySelectorAll('[data-catalog]').forEach(input=>input.oninput=()=>{f[input.dataset.catalog]=input.value;if(input.dataset.catalog==='type'){f.operators=f.operators.filter(k=>catalogOperators(f.type).includes(k));if(!f.operators.length)f.operators=['equal'];draw();}});row.querySelectorAll('[data-operator]').forEach(input=>input.onchange=()=>{f.operators=[...row.querySelectorAll('[data-operator]:checked')].map(i=>i.dataset.operator);});});
  host.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=host.querySelector('[type=submit]');button.disabled=true;try{const saved=await api('/api/settings/site-catalog',{revision:data.revision,fields});data.revision=saved.revision;host.querySelector('[data-catalog-message]').textContent='Field catalog saved. Existing mappings will be checked against this version.';onSaved?.();}catch(error){host.querySelector('[data-catalog-message]').textContent=error.message;}finally{button.disabled=false;}};
 };draw();
}
