import {ruleOperators} from './check-design.js';
import {settingsOperation,settingsPending,settingsFailure} from './settings-form.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const catalogOperators=kind=>Object.keys(ruleOperators).filter(k=>kind==='boolean'?['equal','not_equal','is_null','is_not_null','in','not_in'].includes(k):kind==='string'||!['contains','not_contains','begins_with','ends_with','is_empty','is_not_empty'].includes(k));
export function catalogIssue(fields){
 if(fields.length>500)return {index:500,key:'field',message:'Use at most 500 catalog fields.'};
 const seen=new Set();for(const [index,f]of fields.entries()){
  if(typeof f.field!=='string'||Array.from(f.field).length>200||!(/^[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*$/).test(f.field)||seen.has(f.field))return {index,key:'field',message:'Use a unique table.column mapping, at most 200 characters.'};seen.add(f.field);
  for(const key of ['label','description'])if(typeof f[key]!=='string'||Array.from(f[key]).length>2000||key==='label'&&!f.label.trim())return {index,key,message:key==='label'?'Enter a readable name, at most 2,000 characters.':'Use at most 2,000 characters for the description.'};
  if(!['string','integer','double','boolean'].includes(f.type)||!Array.isArray(f.operators)||!f.operators.length||new Set(f.operators).size!==f.operators.length||f.operators.some(op=>!catalogOperators(f.type).includes(op)))return {index,key:'operators',message:'Select at least one allowed comparison for this value type.'};
 }return null;
}
export async function catalogSettings(host,api,onSaved,run=fn=>fn()){
 const data=await api('/api/settings/site-catalog');let fields=structuredClone(data.fields);const notices=new Map();
 const draw=()=>{
  host.innerHTML=`<p>Configure the names and comparisons agreed with the Site Model team. This catalog starts empty and does not connect to or query their database.</p><form><div class="catalog-fields">${fields.map((f,i)=>`<fieldset data-catalog-row="${i}"><legend>${esc(f.label||'New field')}</legend><label>Display name<input data-catalog="label" required value="${esc(f.label)}"></label><label>Database mapping<input data-catalog="field" required placeholder="table.column" value="${esc(f.field)}"></label><label>Value type<select data-catalog="type">${Object.entries({string:'Text',integer:'Whole number',double:'Number',boolean:'Yes / no'}).map(([k,v])=>`<option value="${k}" ${f.type===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Meaning / agreed usage<textarea data-catalog="description">${esc(f.description)}</textarea></label><details ${notices.has(f)||!f.operators.length?'open':''}><summary>Allowed comparisons (${f.operators.length})</summary>${catalogOperators(f.type).map(op=>`<label class="settings-check"><input type="checkbox" data-operator="${op}" ${f.operators.includes(op)?'checked':''}>${esc(ruleOperators[op])}</label>`).join('')}</details><p data-catalog-error role="status">${esc(notices.get(f)||'')}</p><button type="button" data-remove="${i}">Remove field</button></fieldset>`).join('')}</div><button type="button" data-add-field>Add field</button><p>Existing saved designs retain their catalog version. Changed mappings require review.</p><button type="submit" class="primary">Save field catalog</button><div data-catalog-message role="status"></div></form>`;
  const form=host.querySelector('form');
  host.querySelector('[data-add-field]').onclick=()=>{if(settingsPending(form))return;fields.push({field:'',label:'',type:'string',operators:['equal','not_equal'],description:''});draw();};
  host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(settingsPending(form))return;fields.splice(Number(b.dataset.remove),1);draw();});
  host.querySelectorAll('[data-catalog-row]').forEach(row=>{const f=fields[Number(row.dataset.catalogRow)];row.querySelectorAll('[data-catalog]').forEach(input=>input.oninput=()=>{if(settingsPending(form))return;if(input.validationMessage&&row.querySelector('[data-catalog-error]').textContent===input.validationMessage)row.querySelector('[data-catalog-error]').textContent=notices.get(f)||'';input.setCustomValidity('');f[input.dataset.catalog]=input.value;if(input.dataset.catalog==='field')host.querySelectorAll('[data-catalog-row]').forEach(other=>{const mapping=other.querySelector('[data-catalog="field"]');if(mapping.validationMessage==='Use a unique table.column mapping, at most 200 characters.'){mapping.setCustomValidity('');other.querySelector('[data-catalog-error]').textContent='';}});if(input.dataset.catalog==='type'){const removed=f.operators.filter(k=>!catalogOperators(f.type).includes(k));f.operators=f.operators.filter(k=>catalogOperators(f.type).includes(k));if(removed.length)notices.set(f,'Removed incompatible comparisons: '+removed.map(k=>ruleOperators[k]||k).join(', ')+'. Choose any needed comparison explicitly.');draw();}});row.querySelectorAll('[data-operator]').forEach(input=>input.onchange=()=>{if(settingsPending(form))return;row.querySelectorAll('[data-operator]').forEach(n=>n.setCustomValidity(''));f.operators=[...row.querySelectorAll('[data-operator]:checked')].map(i=>i.dataset.operator);row.querySelector('summary').textContent=`Allowed comparisons (${f.operators.length})`;if(row.querySelector('[data-catalog-error]').textContent==='Select at least one allowed comparison for this value type.')row.querySelector('[data-catalog-error]').textContent=notices.get(f)||'';});});
  form.onsubmit=async e=>{e.preventDefault();if(settingsPending(form))return;const issue=catalogIssue(fields);if(issue){const row=host.querySelector(`[data-catalog-row="${issue.index}"]`),input=row.querySelector(issue.key==='operators'?'[data-operator]':`[data-catalog="${issue.key}"]`);row.querySelector('[data-catalog-error]').textContent=issue.message;if(issue.key==='operators')row.querySelector('details').open=true;input.setCustomValidity(issue.message);input.focus();input.reportValidity?.();return;}
   const payload={revision:data.revision,fields:structuredClone(fields)};
   return settingsOperation(form,run,async()=>{try{const saved=await api('/api/settings/site-catalog',payload);Object.assign(data,saved);host.querySelector('[data-catalog-message]').textContent='Field catalog saved. Existing mappings will be checked against this version.';onSaved?.();}catch(error){settingsFailure(host.querySelector('[data-catalog-message]'),error,{read:()=>api('/api/settings/site-catalog'),local:()=>fields,saved:x=>x.fields,stamp:()=>JSON.stringify(fields),useLocal:latest=>Object.assign(data,latest),useSaved:latest=>{Object.assign(data,latest);fields=structuredClone(latest.fields);draw();host.querySelector('[data-catalog-message]').textContent='Current saved catalog is in the form. Save explicitly if you make changes.';},run});}});
  };
 };draw();
}
